---
title: "playground_location_dataframe"
author: "Niklas Pawelzik"
date: "2024-07-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Create Geocoded Dataframe for Hospital Closures

```{r prepare import dataframes}
# list of all years:
all_years_hospital_reports <- c(
  2022, 
  2021, 
  2020, 
  2019, 
  2018, 
  2017, 
  2016, 
  2015, 
  2014, 
  2013, 
  2012, 
  2010, 
  2008
)
#all_years <- all_years_hospital_reports

path_clean_data_folder <- "./cleaned_data/"
```

```{r import dataframes for each year for location, cases_beds and staff and geocoded dataframe for reference}
# Function to load hospital data files for all years and assign them dynamically
load_hospital_data <- function(prefix) {
  for (year in all_years_hospital_reports) {
    # Construct file path based on the prefix and year
    file_path <- paste0(path_clean_data_folder, prefix, year, ".csv")
    
    # Read the CSV file without displaying column type messages
    # Assign the resulting dataframe to a dynamically named variable in the global environment
    assign(paste0(prefix, year), read_csv(file_path, show_col_types = FALSE), envir = .GlobalEnv)
  }
}

# Load hospital data for each dataset type (location, cases & beds, staff)
load_hospital_data("df_hospital_location_")
load_hospital_data("df_hospital_cases_beds_")
load_hospital_data("df_hospital_staff_")

df_hospital_location_merged_geocoded <- read_csv(paste0(path_clean_data_folder, "df_hospital_location_merged_geocoded", ".csv"), show_col_types = FALSE)
```



```{r function definition year to year comparison}
find_unique_iks <- function(df_current_year, df_next_year) {
  # Extrahiere die IK_Institutionskennzeichen aus beiden DataFrames
  ik_current <- df_current_year$IK_Institutionskennzeichen
  ik_next <- df_next_year$IK_Institutionskennzeichen
  
  # Finde die IKs, die nur im aktuellen Jahr vorhanden sind
  ik_only_current <- setdiff(ik_current, ik_next)
  
  # Filtere den DataFrame des aktuellen Jahres nach diesen IKs
  df_only_current <- df_current_year %>%
    filter(IK_Institutionskennzeichen %in% ik_only_current)
  
  return(df_only_current)
}
```

```{r last appearance in comparison to the next year}
df_last_in_2021 <- find_unique_iks(df_hospital_location_2021, df_hospital_location_2022)
df_last_in_2020 <- find_unique_iks(df_hospital_location_2020, df_hospital_location_2021)
df_last_in_2019 <- find_unique_iks(df_hospital_location_2019, df_hospital_location_2020)
df_last_in_2018 <- find_unique_iks(df_hospital_location_2018, df_hospital_location_2019)
df_last_in_2017 <- find_unique_iks(df_hospital_location_2017, df_hospital_location_2018)
df_last_in_2016 <- find_unique_iks(df_hospital_location_2016, df_hospital_location_2017)
df_last_in_2015 <- find_unique_iks(df_hospital_location_2015, df_hospital_location_2016)
df_last_in_2014 <- find_unique_iks(df_hospital_location_2014, df_hospital_location_2015)
df_last_in_2013 <- find_unique_iks(df_hospital_location_2013, df_hospital_location_2014)
df_last_in_2012 <- find_unique_iks(df_hospital_location_2012, df_hospital_location_2013)
df_last_in_2010 <- find_unique_iks(df_hospital_location_2010, df_hospital_location_2012)
df_last_in_2008 <- find_unique_iks(df_hospital_location_2008, df_hospital_location_2010)

# given the apparent data issue of 2016 I will ignore that year and for 2015, combine 2016 and 2017 to compare
df_hospital_location_2017_for2015 <- as.data.frame(lapply(df_hospital_location_2017, as.character))

df_hospital_location_2016_for2015 <- as.data.frame(lapply(df_hospital_location_2016, as.character))

df_closed_hospitals_20162017 <- bind_rows(
  df_hospital_location_2017_for2015,
  df_hospital_location_2016_for2015)
df_last_in_2015_20162017 <- find_unique_iks(df_hospital_location_2015, df_closed_hospitals_20162017)
```

```{r review IKs for last appearances, 2008 manual check hospitals for closures}
df_last_in_2008 %>%
  distinct(IK_Institutionskennzeichen) %>%
  nrow()

# 990800010 Davos needs to be excluded
# 260100717 subsequent years have data
# 260101002 subsequent years have data
# 260101079 subsequent years have data
# 260101411 subsequent years have data
# 260101466 closed: https://www.abendblatt.de/region/stormarn/article108069650/Klinik-Schliessung-Ambulante-Versorgung-geht-weiter.html
# 260101763 subsequent years have data
# 260102014 subsequent years have data
# 260102025 subsequent years have IK 260102423
# 260102229 subsequent years have data

# 260100078 Uniklinikum, IK 260102343 for same address
# 260100249 Uniklinikum, IK 260102354 for same address
# 260200989 Uniklinikum, IK 260200013 for same address
# 260200331 subsequent years IK 260201194 and also two years 260200752 for same address
# 260200796 merged and moved in 2014: Die Fachklinik Helmsweg wird ab dem 1. September 2014 in das Asklepios Klinikum Harburg integriert.
# 260310232 subsequent years have data
# 260310403 merged and taken over by Universitätsklinik in 2012/2013: https://www.hna.de/lokales/goettingen/klinikum-streckt-fuehler-2615744.html
# 260320278 subsequent years have data
# 260321235 subsequent year has IK 260321042, then 570320085
# 260330145 closed in 2013: "Im Jahr 2013 hat der Betreiber Allgemeines Krankenhaus (AKH) die Nutzung als geriatrische Klinik im St.-Josef-Stift aufgegeben" https://celler-presse.de/2014/07/08/anschlussverwendung-josefstift-stadt-plant-ein-hotel-an-dieser-stelle/

# 260330715 subsequent years have data
# 260340294 subsequent years have data
# 260340728 subsequent years have data, but seem to have moved within city
# 260341057 subsequent years have data
# 260510699 subsequent years have data
# 260510780 unclear, maybe no longer a hospital? https://www.ameos.de/klinikum-st-marien-oberhausen/
# 260510859 seems to be closed and turned into a MVZ: https://www.waterboelles.de/archives/11269-Hausarztpraxis-in-der-Duenkeloh-Klinik-in-neuen-Haenden.html
# 260511473 still open: https://www.evkln.de/evangelisches-krankenhaus-dinslaken.html
# 260530762 subsequent years have data but moved within city
# 260530773 subsequent years have data

# 260531080 is closed: https://www.oberberg-aktuell.de/index.php?id=144&tx_ttnews%5Btt_news%5D=38757
# 260055040 IK for same address: 260551154
# 260550437 still open: https://www.klinikum-westmuensterland.de/st-marien-hospital-vreden/
# 260550471 still open: https://christophorus-kliniken.de/kontakt-anfahrt/
# 260055040 IK for same address: 260551154
# 260570168 unclear
# 265570453 subsequent years IK 260570453
# 260570523 subsequent year IK 260570486
# 260571648 closed in 2010: https://www.westfalen-blatt.de/owl/kreis-paderborn/bueren/datenschutz-lauft-ins-leere-799078
# 260590889 subsequent years have IK 260593461

# 260590890 subsequent year has IK 260593030
# 260590947 subsequent years have IK 260593030
# 260591027 subsequent years have IK 260593030
# 260591129 subsequent years have data
# 260591174 subsequent year has IK 260593085
# 260591185 IK 260593085
# 260591254 subsequent years have IK 260593085
# 260591403 subsequent years have 
# 260592459 closed, owner went into Insolvenz in 2011, https://www.wp.de/staedte/wittgenstein/article7035190/insolventes-klinik-unternehmen-verklagt-laaspher-handwerker.html
# 260610246 for subsequent years IK 260610122

# 260610326 subsequent years has IK 260650369
# 260610725 subsequent years have data
# 260611065 subsequent years have IK 260611054
# 260611635 subsequent years have IK 260611624
# 260620453 subsequent years have IK 260610315
# 260620464 subsequent years have IK 260610315
# 260620545 is closed, around 2010: https://www.hna.de/lokales/fritzlar-homberg/homberg-efze-ort305309/fuer-asklepios-gibt-es-keine-alternative-90008349.html
# 260620636 subsequent years have data
# 260621216 subsequent years have data
# 260640721 closed in 2019: https://www.giessener-allgemeine.de/hessen/parkinsonklinik-oktober-schluss-12120111.html

# 260650154 still open: https://ao-marburg.de/?ngt=w7e1c0e141c30e71cd03556170556387
# 260650201 subsequent years have data
# 260650303 merged with another hospital and moved in 2021: https://www.kma-online.de/aktuelles/klinik-news/detail/klinik-waldhof-elgershausen-zieht-ins-evangelische-krankenhaus-mittelhessen-a-44731
# 260660236 unclear
# 260710851 subsequent years have data
# 260720421 closed early 2014: https://www.neuerburg-eifel.de/index.php/buergerinfo/787-neuerburger-krankenhaus-wird-geschlossen
# 260810135 subsequent years: IK 260812569
# 260810534 IK 260812273 then closed in 2015: https://www.teckbote.de/geschichte-der-klinik-endet-nach-150-jahren_arid-85727.html
# 260811136 closed in 2012: "Schließung des Krankenhauses im Sommer 2012", https://www.swp.de/lokales/gaildorf/gaildorf-krankenhaus-klinikum-pylon-44029035.html
# 260811476 subsequent years IK 260812649

# 260811739 closed in 2014: https://www.teckbote.de/aerpah-klinik-muss-schlie%C3%9Fen_arid-79116.html
# 260812002 subsequent years have data
# 260812160 closed in 2010, only preview, article no longer available: "Nachnutzung für Gebäude Hofstatt 7 Rems-Zeitung https://remszeitung.de › ... › Schwäbisch Gmünd 19.05.2011 "
# 260811249 subsequent years IK 260812558
# 260820694 subsequent years IK 260822275
# 260820876 still open: https://www.kma-online.de/aktuelles/koepfe/detail/siloah-trudpert-klinikum-verpflichtet-neue-pflegedirektorin-51432
# 260820956 subsequent years have IK 260821025
# 260821332 subsequent years have data
# 260821639 subsequent year has IK 260820466
# 260830618 subsequent years have data

# 510836022  subsequent years have data IK 260830618
# 660810055 subsequent years have data IK 260833531
# 260830914 still open: https://offenburg-kehl.ortenau-klinikum.de/zentren-schwerpunkte/betriebsstelle-offenburg-st-josefsklinik/
# 490830776 subsequent years have IK 260831072
# 260833132 subsequent year have data
# 260831675 closed in 2011: https://www.badische-zeitung.de/das-spital-in-schoenau-macht-zu
# 260840335 subsequent years have data
# 260841018 subsequent years have IK 260841041 Standort 03
# 260841029 subsequent years have IK 260841041 Standort 02
# 260910034 seems to be closed: "ehemalige Reiserklinik" https://www.donaukurier.de/archiv/aus-der-reiser-klinik-werden-vier-tageskliniken-3527476

# 260910250 subsequent years have IK 260914631
# 490910875 subsequent years have IK 260912229
# 260912387 subsequent years have IK 260914642
# 260912571 subsequent years have IK 260914653
# 260914506 merged with subsequent hospital, both still exist https://www.ilmtalkliniken.de/ with IK 260913117
# 260914506 merged with previous hospital, both still exist https://www.ilmtalkliniken.de/ with IK 260913117
# 260914027 subsequent years have data
# 260914083 subsequent years have data
# 260914298 subsequent years have data
# 260910294 IK 260914492 for this and subsequent years

# 260920229 subsequent years have IK 260921231
# 260920241 still open: https://www.frg-kliniken.de/
# 260920252 subsequent year has data
# 260920888 subsequent years have IK 260921162
# 260920899 subsequent year have IK 260921162, 260921117, 260921151, 260921140, 260921139, still open: https://ge-passau.de/klinik-krankenhaus/krankenhaus-vilshofen/
# 260920902 later years have IK 260921162
# 260930458 subsequent year has IK 260930447
# 260930539 no longer Akutkrankenhaus since 2020: https://www.frankenpost.de/inhalt.waldsassen-waldsassen-verliert-akut-krankenhaus.9bcd015e-f49d-40a0-aa51-b06262646402.html
# 260930595 subsequent years have data
# 260940110 subsequent year has IK 260940109, ff have 260940109 and Standortnummer 02

# 260940392 still open: https://www.kliniken-hochfranken.de/patienten-besucher/besucherinformationen
# 260940449 subsequent years have data
# 260940688 subsequent years have data
# 260950373 data for IK 260950419, Standortnummer 02
# 260950373 data for IK 260950419, Standortnummer 01
# 260970366 subsequent years have data, change of hospital in 2014? then IK 260970388, see below 
# 260970388 subsequent years have data, also IK 260970366, see above
# 260970402 subsequent years have data
# 510975269 still open: https://donkliniken.de/klinik-oettingen/
# 260970480 subsequent years have data

# 261100252 subsequent years have data
# 261100456 subsequent years have data
# 261101219 still open: https://tww-berlin.de/kliniken/psychiatrie/behandlungsformate/tagesklinik-lankwitz/
# 261101583 subsequent year has data
# 261101765 subsequent years have data
# 261201221 seem to still be open
# 261201221 seem to still be open
# 261300130 subsequent years have data
# 261300210 subsequent years have data with IK 261300129
# 261300425 subsequent years have data

# 261400277 subsequent years have data with IK 261401303
# 261401007 is closed before 2013: https://www.saechsische.de/plus/einstige-helios-klinik-wird-wohnpark-2610970.html
# 261401132 UNCLEAR
# 261401369 subsequent years have data
# 261510065 more data under IK 261510043
# 261601203 more data for subsequent years
# 261601203 more data for subsequent years
# 261601225 seems to be open: https://www.mdr.de/nachrichten/deutschland/politik/krankenhaus-reform-chirurgie-kosten-100.html
# 510320234 more data for subsequent years
# 510330065 data for years with IK 510335903

# 510573365 data for next year under IK 510571205
# 510642712 more data for subsequent years
# 510961456 unclear, maps still has the institution but no website
# 511402393 unclear, seems to be still open: https://www.helios-gesundheit.de/standorte-angebote/kliniken/leipzig/aufenthalt/aufnahme-besucher/aufnahme-soteria/
# 511430466 unclear, seems to be still open: https://www.helios-gesundheit.de/standorte-angebote/kliniken/leipzig/aufenthalt/aufnahme-besucher/aufnahme-soteria/
# 512103930 data for subsequent years IK 260102412

## 260101466, 260330145, 260510859, 260531080, 260571648, 260592459, 260620545, 260640721, 260720421, 260811136, 260811739, 260812160, 260831675, 260910034, 260930539, 261401007

```

```{r identification of confirmed closures with final mention in 2008 as per manual review in chunk above}
IK_closed_hospitals_2008 <- c(260101466, 260330145, 260510859, 260531080, 260571648, 260592459, 260620545, 260640721, 260720421, 260811136, 260811739, 260812160, 260831675, 260910034, 260930539, 261401007)


df_closed_hospitals_2008 <- df_last_in_2008 %>%
  filter(IK_Institutionskennzeichen %in% IK_closed_hospitals_2008) %>%
  mutate(across(everything(), as.character))
```


```{r review IKs for last appearances, 2010 manual check hospitals for closures}
df_last_in_2010 %>%
  distinct(IK_Institutionskennzeichen) %>%
  nrow()


# 510000248 should be excluded altogether since Davos (Switzerland), also IK 990800010 and 260000066
# 512100210 more IKs 260100023, 510106995, 201304613, data for subsequent years
# 510106995 more IKs 260100023, 512100210, 201304613, data for subsequent years
# 201304613 more IKs 260100023, 512100210, 510106995, data for subsequent years
# 512104145 data exists for 2018 ff again (260101091, 510106882, 512104145, 260102662)
# 510106882 data exists for 2018 ff again  (260101091, 510106882, 512104145, 260102662)
# 510100330 data exists for 2015
# 260201070 IK 260200046 for early years both IK, subsequent years only 260200046
# 260310722 closed probably in April 2012 https://www.aerztezeitung.de/Wirtschaft/Eine-bittere-Erfahrung-Die-Klinik-ist-insolvent-345436.html
# 260310744 subsequent years have data

# 260320542 ownership change and merge into other hopsital, location closed end of 2012/beginning of 2013: https://www.krh.de/news/2011/hautklinik
# 260320871 still open, subsequent data under IK 260321587
# 260320882 closed in 2012: https://www.hna.de/lokales/northeim/einbeck-ort55445/klinik-stadtoldendorf-bald-dicht-2444656.html
# 260321042 data for prior year IK 260321235, subsequent years 570320085
# 260330931 data also under IK 260330680, 460332706
# 460332706 data also under IK 260330680, 260330931
# 490340352 other years IK 260340410
# 260340421 subsequent years 260342285
# 540340125 other years IK 260341115, 260341514
# 260341514 other years IK 260341115, 540340125

# 260510063 subsequent years 260513271, 260500254
# 260510245 subsequent years IK 260513282
# 260510267 closed mit 2013: "Im Zuge der wirtschaftlichen Sanierung des KKD wurde das St. Barbara-Hospital geschlossen und die zuletzt dort beheimateten Fachabteilungen zum 1. Juli 2013 an das St. Johannes-Hospital in Duisburg-Hamborn abgegeben.", https://de.wikipedia.org/wiki/St._Barbara-Hospital_(Duisburg)
# 260510278 subsequent data IK 260513282
# 260510438 subsequent data IK 260512021
# 260510564 data for subsequent years
# 260510848 subsequent years with IK 260513259
# 260510928 seems to be part of IK 260510939 in subsequent years
# 260511155 hospital closed: https://rp-online.de/nrw/staedte/langenfeld/abriss-st-josef-hospital_aid-38035775
# 260511213 seems to be still open in subsequent years:  https://supertipp-online.de/nachrichten/velbert/sucht-symposium-in-langenberg-id18383

# 260512054 still open, part of another hospital, https://www.petrus-krankenhaus-wuppertal.de/medizin/geriatrische-rehabilitation
# 260530341 subsequent years IK 260532888
# 260530717 subsequent years IK 260532811
# 490532161 also IK 260530977
# 260531091 still open in subsequent years, probably not as a full hospital: https://www.oberberg-nachrichten.de/archiv/nach-dem-examen-ins-krankenhaus-39-erfolgreiche-absolventen/ 
# 260531137 subsequent years IK 260532935
# 510536826 also IK 260531159 (main for subsequent years), 500535415, 500536520
# 500535415 also IK 260531159 (main for subsequent years), 510536826, 500536520
# 500536520 also IK 260531159 (main for subsequent years), 510536826, 500535415
# 260531989 other years IK 260531967

# 260531989 other years IK 260531967
# 260550028 still open: https://kern.ruhr/unser-leistungsverbund/krankenhaeuser/st-antonius-krankenhaus
# 260550073 still open: https://kern.ruhr/unser-leistungsverbund/krankenhaeuser/st-josef-hospital
# 260550164 other years IK 260551416
# 260550379 subsequent year IK 260550266, Standortnumer 02
# 260550563 subsequent years IK 260590219 
# 260550632 still open: https://kern.ruhr/unser-leistungsverbund/krankenhaeuser/st-sixtus-hospital-haltern
# 260550654 still open: https://kern.ruhr/unser-leistungsverbund/krankenhaeuser/gertrudis-hospital-westerholt
# 260550676 still open: https://kern.ruhr/unser-leistungsverbund/krankenhaeuser/marien-hospital-marl
# 260550665 other IK seems to be 260551165

# 260551779 still open: https://st-elisabeth-krankenhaus-dorsten.de/
# 260570204 still open: https://www.sankt-vinzenz.de/sv/index.php
# 260570317 still open: https://www.mathilden-hospital.de/mat/index.php
# 260570340 subsequent years part of a merge: IK 260570328
# 260570373 still open: https://steinheim.khwe.de/de/home
# 260570453 still open, subsequent years have data
# 260570738 still open, subsequent years IK 260570681, then IK 260570692
# 260571114 still open: https://www.gollwitzer-meier-klinik.de/
# 260590366 subsequent year data 260592084 Standortnummer 02
# 260590594 closed in 2013: https://www.wp.de/staedte/ennepetal-gevelsberg-schwelm/article7545364/marienhospital-in-schwelm-wird-geschlossen.html

# 260590663 closed but only end of 2023: "Der Krankenhausbetrieb im Marienhospital wurde Ende August 2023 eingestellt" https://klinikum-hochsauerland.de/das-klinikum/standorte/marienhospital
# 260590674 subsequent years IK 260593600 (Standortnummer 02)
# 260590685 subsequent years 260593600 (Standortnummer 03)
# 260590787 closed end of 2012: https://www.wp.de/staedte/meschede-und-umland/article7317541/st-georg-krankenhaus-in-fredeburg-schliesst-mitarbeiter-werden-entlassen.html
# 260590936 still open, only 2013 missing, 2013 is data flaw and should be corrected as well  
# 260591049 still open, data for other years exists
# 260591232 still open, subsequent years IK 260591221
# 260591993 still open, subsequent years IK 260591221
# 442590224 still open, subsequent years IK 260591221
# 260591298 subsequent years IK 260591334

# 260592437 still open https://kkh-hagen.de/
# 260592415 closed end of 2011: "beabsichtigt, den Krankenhausbetrieb im Marienkrankenhaus Wimbern zum 31. Dezember 2011 einzustellen." https://www.lokalkompass.de/wickede/c-ueberregionales/dicht-marienkrankenhaus-wimbern_a99369
# 260590162 IK 260593096
# 260590173 IK 260593109
# 260590151 IK 260593110
# 260610598 subsequent years IK 260641642
# 260610703 subsequent years IK 260610690
# 260610781 subsequent years IK 260610770
# 260611602 only next year missing, subsequent years there
# 260611942 subsequent years have IK 260641619

# 260620055 subsequent years IK 260660895
# 260620102 closed in 2011, probably merged and moved into IK 260660826: https://www.hna.de/kassel/ende-eines-traditionshauses-passiert-kinderkrankenhaus-park-schoenfeld-1470454.html
# 260620124 changed owner twice before closing in 2016: https://www.hna.de/kassel/ende-koch-klinik-kassel-12972223.html
# 260620237 still open: https://rhoen-klinik.de/
# 260620293 closed in March 2012: https://www.hna.de/lokales/rotenburg-bebra/juwel-wird-plattgemacht-1494404.html
# 260620339 subsequent two years IK 260660826, then IK 260660862
# 260620340 subsequent years IK 260660862
# 260620373 closed before end of 2014: https://www.hna.de/lokales/hofgeismar/bad-karlshafen-ort74607/klinik-helmarshausen-neuen-paechter-4504319.html
# 260620567 closed in 2023: https://www.hna.de/lokales/melsungen/melsungen-ort45520/asklepios-schliesst-klinik-melsungen-patientenversorgung-ab-januar-in-schwalmstadt-91977169.html
# 260621001 still open, probably had a merge: https://klinikum-werra-meissner.de/klinikum/kontakt/

# 260621012 subsequent years: IK 260660873
# 260640322 still open: https://www.parkklinik-bad-nauheim.de/kontakt/ (same like subsequent)
# 540640297 still open: https://www.parkklinik-bad-nauheim.de/kontakt/ (same like prior)
# 260640652 subsequent years have data
# 510644849 other years have IK 260641403
# 260660327 other years have IK 260660134
# 260660511 other years have IK 260660839
# 260710098 other years have IK 260711965
# 260710624 other years have IK 260710646
# 260710624 other years have IK 260710646

# 260711033 other years have IK 260711000
# 260711204 mixed hospitals, three locations, impossible to identify correct one
# 260711204 mixed hospitals, three locations, impossible to identify correct one
# 260711215 other years have IK 260711852
# 260720012 subsequent years IK 260720487, 260720502
# 260720012 subsequent years IK 260720487, 260720502
# 260720056 closed since 2021/2022
# 260720147 unclear
# 260720227 still open: https://www.marienhaus-klinikum-eifel.de/unserklinikum/standort/st-elisabeth-gerolstein
# 490730673 other years IK 260730138

# 260730365 other years IK 260730478, mostly Standortnummer 99
# 260730708 other years IK 260731219
# 510816288 later year with IK 260810293, still open: https://www.fbkh.org/kontakt/
# 260810578 later year with IK 260810589
# 260812433 subsequent years IK 260810590 (like below)
# 510814652 subsequent years IK 260810590 (like above)
# 260810603 unclear, no info found
# 260810750 subsequent years IK 260812763
# 260810976 for one year (2017), there is data on IK 260810794, hopsital exists https://www.slk-kliniken.de/geriatrische-reha/unser-profil
# 510814685 other years have IK 260811498

# 260820785 only subsequent year missing
# 260820843 closed in 2011: https://www.stimme.de/wirtschaft/baden-wuerttemberg/wi/srh-fachkrankenhaus-neckargemuend-wird-geschlossen-art-2211064
# 510825542 still open, recent years has data again under a different name, hopsital still exists: https://www.kn-calw.de/anfahrt-lage
# 510818532 still open, recent years has data again under a different name, hopsital still exists: https://www.kn-calw.de/anfahrt-lage
# 260830060 seems to be closed since 2011: https://www.badische-zeitung.de/st-elisabeth-krankenhaus-wird-geschlossen
# 260830344 probably restructured as part of https://www.uniklinik-freiburg.de/herzzentrum.html
# 260830399 subsequent years have data again
# 260833121 subsequent years have data again
# 260833030 still open, subsequent years under IK 260833531 mixed with other hospitals
# 260833052 still open, subsequent years under IK 260833531 mixed with other hospitals

# 540830162 still open, subsequent years under IK 260833531 mixed with other hospitals
# 260831094 closed in 2011: https://www.aerzteblatt.de/archiv/111078/Krankenhaussterben-in-Suedbaden-Wenn-ein-Stueck-Heimat-verloren-geht
# 260831390 subsequent years IK 260833449
# 260831642 closed early 2012
# 260831846 unclear
# 510814516 still open with a lot of IK, for instance 260832676
# 510834428 still open with a lot of IK, for instance 260832676
# 260833029 still open with a lot of IK, for instance 260832676
# 260832789 subsequent years have data
# 260840153 subsequent years have 260840164

# 260841143 subsequent years have IK 260841928
# 260841483 subsequent years have IK 260841483
# 260841713 closed mid 2014: https://www.schwaebische.de/regional/allgaeu/isny/erinnerungen-ans-krankenhaus-isny-sind-noch-frisch-2243995
# 260910682 subsequent years IK 260910693
# 260910682 subsequent years IK 260910693

## 260310722, 260320542, 260320882, 260510267, 260511155, 260590594, 260590663, 260590787, 260592415, 260620102, 260620293, 260620373, 260620567, 260720056, 260830060, 260831094, 260831642, 260841713
```

```{r identification of confirmed closures with final mention in 2010 as per manual review in chunk above}
IK_closed_hospitals_2010 <- c(260310722, 260320542, 260320882, 260510267, 260511155, 260590594, 260590663, 260590787, 260592415, 260620102, 260620293, 260620373, 260620567, 260720056, 260830060, 260831094, 260831642, 260841713)


df_closed_hospitals_2010 <- df_last_in_2010 %>%
  filter(IK_Institutionskennzeichen %in% IK_closed_hospitals_2010) %>%
  mutate(across(everything(), as.character))
```

```{r review IKs for last appearances, 2012 manual check hospitals for closures}
df_last_in_2012 %>%
  distinct(IK_Institutionskennzeichen) %>%
  nrow()


#260101547 data exists in subsequent years again
#260101547 data exists in subsequent years again
#260101547 data exists in subsequent years again
#260101547 data exists in subsequent years again
#260101547 data exists in subsequent years again
#269310744 still open, other years have IK 260310744
#260311073 still open, subsequent years have IK 260311302
#260320109 still open, only 2013 missing, subsequently IK 260321703
#260320655 still open, subsequent years IK 260321714
#260330418 still open, subsequent years IK 260331135

#260330463 closed end of 2015: https://www.abendblatt.de/hamburg/harburg/article206811193/Klinik-Salzhausen-schliesst-nach-118-Jahren.html
#260340318 closed 2014/2015 https://www.aerzteblatt.de/nachrichten/60478/Aus-fuer-Klinik-im-niedersaechsischen-Dissen
#260340352 no info found, probably closed
#260511451 closed in 2014: https://rp-online.de/nrw/staedte/willich/schliessung-vor-10-jahren-erinnerungen-an-das-willicher-katharinen-hospital_aid-115498983
#260512167 still open, only 2013 missing
#260530169 still open https://kliniken-bonn.gfo-online.de/ueber-uns/unser-haus
#260531115 still open, only subsequent year missing
#260531126 still open: https://www.klinikum-oberberg.de/standorte/kreiskrankenhaus-waldbroel/
#260531273 still open, only 2013 missing
#260551757 still open, only 2013 missing

#260550222 still open, only 2013 missing
#260570328 still open: https://www.westfalen-blatt.de/owl/kreis-hoexter/brakel/kwe-service-krankenhaus-cafeteria-driburg-brakel-2896491?&npg
#260570328 still open: https://www.westfalen-blatt.de/owl/kreis-hoexter/brakel/kwe-service-krankenhaus-cafeteria-driburg-brakel-2896491?&npg
#260590093 data there for 2014,  still exists https://www.klinikum-bochum.de/marien-hospital-wattenscheid/standort.html
#260591094 still open, subsequent data under IK 260591107
#260591481 still open, recent years has data under IK 260591619 as part of Klinikum Westfalen
#260591492 still open, for recent years data under IK 260591619 as part of Klinikum Westfalen
#260592723 data for some subsequent years https://www.fliedner.de/de/seelische_gesundheit/fliedner_klinik_gevelsberg/fliedner_klinik_gevelsberg.php
#260593461 for 2009 under IK 260590889, info for subsequent year under 260593461 closed early 2017 "Heute (Dienstag, 3. Januar 2017) hat das Altenaer Krankenhaus dichtgemacht."https://altena-online.de/st_vinzenz_krankenhaus_geschlossen/
#260610348 still open, subsequent years IK 260610337

#260611782 still open, subsequent years reorganized and IK 260641722
#260611806 still open, subsequent years IK 260641722
#260611806 still open, subsequent years IK 260641722
#NA
#260720487 still open, previous years IK 260720012, subsequent years IK 260720502
#260720487 still open, previous years IK 260720012, subsequent years IK 260720502
#260720487 still open, previous years IK 260720012, subsequent years IK 260720502
#260730332 closed in 2018: https://nibelungen-kurier.de/hochstift-schliesst-bis-2018/
#260810705 seems to be closed
#260810738 seems to be closed

#260811034 data on subsequent years under IK 260811089
#260830903 different IKs, subsequent years has IK 260833531
#260832552 only 2013 missing, subsequent years have data
#260840062 subsequent years IK 260840028
#260840277 subsequent years IK 260840288 Standortnummer 02
#260840302 subsequent years IK 260840288 Standortnummer 03 for most years
#260911193 still open: https://www.kna-online.de/
#260911217 still open: https://www.kna-online.de/
#260913823 only 2013 missing, subsequent years have data
#260913889 stayed open until 2023 at least: https://www.kma-online.de/aktuelles/klinik-news/detail/warum-die-fachklinik-in-lenggries-sofort-schliessen-muss-50361

#260914196 2013 missing, subsequent years have data, previous years do not show
#260920365 still open: https://www.lakumed.de/fachgebiete/schlossklinik-rottenburg
#260921184 other years most likely part of "DONAUISAR Klinikum Deggendorf", IK 260920127
#260920252 no longer stationär apparently? https://www.frg-kliniken.de/medizin/uebersicht-standortsuche no findings for this PLZ or Ort
#261100913 subsequent years IK 261102390, moved within the PLZ to different address
#261201458 subsequent years IK 261201481
#261500234 subsequent years IK 261500984
#261500256 only 2013 is missing
#261500519 subsequent years probably IK 261530230 taken over by AMEOS
#261500531 subsequent years IK 261500984

#510571498 subsequent years have data, 2013 missing

## 260330463, 260340318, 260340352, 260511451, 260730332, 260920252
```

```{r review IKs for last appearances, 2012 manual check hospitals for closures}
IK_closed_hospitals_2012 <- c(260330463, 260340318, 260340352, 260511451, 260730332, 260920252)


df_closed_hospitals_2012 <- df_last_in_2012 %>%
  filter(IK_Institutionskennzeichen %in% IK_closed_hospitals_2012) %>%
  mutate(across(everything(), as.character))
```

```{r review IKs for last appearances, 2013 manual check hospitals for closures}
df_last_in_2013 %>%
  distinct(IK_Institutionskennzeichen) %>%
  nrow()


#260000066 should be disregarded as it is in Switzerland
#260101024 still open, only 2014 and 2015 are missing
#260101763 still open, https://www.klinik-klosterstrasse.de/kontakt-anfahrt.html probably data problem, subsequent years has "260102673"
#260102149 still open, only 2014 is missing
#260200159 still open, subsequent years 260201229
#260320564 still open, subsequent years 260321781, 260320575, 260320542
#260320575 still open 260321781, 260320542
#260320746 still open, a lot of institutions for this address, also 260320757 and 260321747
#260320826 subsequent years 260321758
#260320223 unclear

#260330258 still open, data for most other years
#260330704 seems to be closed
#260341079 is closed: https://www.ndr.de/nachrichten/niedersachsen/oldenburg_ostfriesland/Wilhelmshaven-St-Willehad-Hospital-wird-neue-Sammelunterkunft,aktuelloldenburg14368.html
#260510553 still open: merged, IK 260512101
#260530660 still open, only 2014 is missing
#260550745 still open: https://ukm-mhs.de/fachgebiete/psychosomatik-und-psychotherapie
#260570431 subsequent years have data again
#206570453 still open, other years have IK 260570453
#260570910 still open: https://www.st-josefs.de/
#260590550 data for 2017 under IK  260590071

#260592233 still open, https://www.maerkische-kliniken.de/klinikum-luedenscheid.html other years have 260590969
#260612077 owner changed: https://www.wetterauer-zeitung.de/wetterau/bad-nauheim-ort78877/harvey-klinik-helios-wird-kerckhoff-12069296.html taken over by pre-exisiting hopsital 260611862 
#260620237 still open: https://rhoen-klinik.de/
#260620738 still open, IK 260620066 (Standort 2)
#260660826 still open, IK 260620011
#260660826 still open, IK 260620011
#260660826 still open, IK 260620011
#260660826 still open, IK 260620011
#260731208 closed, probably 2018, still open in 2017: https://nibelungen-kurier.de/klinikum-worms-standort-hochstift-schliesst-voraussichtlich-im-2-quartal-2018/
#260830685 still open, IK 260833519 Standort 99

#260830812 data until 2019 under IK 260833494; still exists: https://www.ortenau-klinikum.de/ (klinik wird offenbar mutmasslich 2027 geschlossen), https://www.kehl.de/nachnutzung+krankenhaus
#260830845 still open, IK 260833520 
#260830890 data under 260833519 and 260833508 until 2019, then closed: https://www.bo.de/lokales/achern-oberkirch/runder-tisch-kritisiert-umzug-des-mvz-ins-krankenhausgebaude-oberkirch
#260830992 still open: https://wolfach.ortenau-klinikum.de/
#260833461 for subsequent years data under IK 260833450; existiert, ist mutmasslich organisatorisch in Uniklinik eingegliedert: https://www.uniklinik-freiburg.de/so-finden-sie-uns/lageplaene.html 
#260950651 still open: https://www.kliniken-nea.de/home 260950351
#260950783 subsequent years IK 260950237 and 260950011
#260960592 subsequent years IK 260960605 (taken over by Klinikum Main-Spessart?)
#260970388 subsequent years 260970366 and 260972233
#260970402 still open: https://donkliniken.de/, more data with 260970366

#260970754 closed in 2016: "Seit dem 31. März 2016 ist die Schlossbergklinik in Oberstaufen geschlossen – jetzt ist sie verkauft." https://www.b4bschwaben.de/b4b-nachrichten/kempten-oberallgaeu_artikel,-geiger-unternehmensgruppe-kauft-schlossbergklinik-oberstaufen-_arid,259537.html
#261101583 still open, subsequent years IK 261102323, since 2020 with Standortnummer 772478000 instead of 00
#261102129 closed by end of 2013 after 7 years: https://www.kma-online.de/aktuelles/klinik-news/detail/das-verflixte-siebte-jahr-a-27204
#261300631 still open, subsequent years IK 261301120, since 2020 with Standortnummer 771830000 instead of 00
#261300711 subsequent years 261301108, apparently moved in 2017/18 to "Carl-Hopp-Straße, 19a, 18069, Rostock"
#261300711 subsequent years 261301108, apparently moved in 2017/18 to "Carl-Hopp-Straße, 19a, 18069, Rostock"
#261300711 subsequent years 261301108, apparently moved in 2017/18 to "Carl-Hopp-Straße, 19a, 18069, Rostock"
#261300766 still open https://www.ggp-gruppe.de/kip/teilstationaer/tagesklinik-und-pia-fuer-kinder-und-jugendliche
#261300982 still open https://www.nnn.de/lokales/rostock/artikel/neuer-spielplatz-fuer-kinder-mit-psychischer-stoerungen-in-rostock-45327890
#216500256 still open, all other years have IK 261500256

#510642197 still open, prior years have IK 510642197, subsequent years have  260610849
#510912149 still open, all other years have IK 260913823

## 260320223, 260330704, 260341079, 260731208, 260830890, 260970754, 261102129 
```

```{r review IKs for last appearances, 2013 manual check hospitals for closures}
IK_closed_hospitals_2013 <- c(260320223, 260330704, 260341079, 260731208, 260830890, 260970754, 261102129)


df_closed_hospitals_2013 <- df_last_in_2013 %>%
  filter(IK_Institutionskennzeichen %in% IK_closed_hospitals_2013) %>%
  mutate(across(everything(), as.character))
```


```{r review IKs for last appearances, 2014 manual check hospitals for closures}
df_last_in_2014 %>%
  distinct(IK_Institutionskennzeichen) %>%
  nrow()

# 260100125 still open https://www.lubinus-stiftung.de/start-sek.html, subsequent years IK 260100170
# 260101411 still open https://www.nordblick.de/standorte/augenklinik-bellevue/, subsequent years IK 260102695
# 260102069 closed since end of 2019: https://www.shz.de/lokales/flensburg/artikel/flensburger-foerde-klinik-schliesst-ende-2019-41720248
# 510100330 still open https://www.curtius-klinik.de/#Anfahrt, for some years two IKs with 260102149
# 260200752 still open: https://www.asklepios.com/hamburg/harburg/
# 260310107 still open, only 2015 is missing
# 260320860 probably closed, does not appear anymore 
# 260321532 closed in 2015 https://www.krh.de/news/2015/umzug-springe
# 260330474 is closed: https://www.abendblatt.de/region/harburg-landkreis/article239730731/Ehemaliges-Krankenhaus-wird-Unterkunft-fuer-Gefluechtete.html
# 260340283 merged with below from same town, still open IK 260300332, 260340283, 260300081 https://www.delme-klinikum.de/

# 260340294 merged with above from same town, still open IK 260300332, 260340283, 260300081
# 260340307 still open: https://www.franziskushospital-lohne.de/
# 260340808 still open, subsequently IK 260342310
# 260510779 still open https://www.radiooberhausen.de/artikel/schweizer-holding-uebernimmt-kko-395811.html, after take-over reports start again under IK 260510791
# 260510779 still open https://www.ameos.eu/oberhausen https://www.radiooberhausen.de/artikel/schweizer-holding-uebernimmt-kko-395811.html, after take-over reports start again under IK 260510791
# 260510779 still open https://www.ameos.eu/oberhausen https://www.radiooberhausen.de/artikel/schweizer-holding-uebernimmt-kko-395811.html, after take-over reports start again under IK 260510791
# 230530660 still exists, all other years have 260530660
# 260531251 closed in 2014 "Im November 2014 wurde das Krankenhaus geschlossen"
# 260550756 still exists https://www.maria-josef-hospital.de/startseite.html
# 260590093 still exists https://www.klinikum-bochum.de/marien-hospital-wattenscheid/standort.html

# 590260106 still exists https://www.augusta-kliniken.de/standorte.html all other years have 260590106
# 260590231 closed, since 2015 different hospital with IK 260593724
# 260593461 closed early 2017 "Heute (Dienstag, 3. Januar 2017) hat das Altenaer Krankenhaus dichtgemacht." https://altena-online.de/st_vinzenz_krankenhaus_geschlossen/
# 260641642 closed https://www.rnz.de/region/metropolregion-mannheim_artikel,-Metropolregion-Luisenkrankenhaus-in-Lindenfels-geschlossen-_arid,210718.html "Luisenkrankenhaus in Lindenfels geschlossen"
# 260710270 still open, subsequent years merged to "Verbundkrankenhaus Linz-Remagen" with IK 260710873 https://www.krankenhaus-linz-remagen.de/
# 260710793 still open https://www.gk.de/krankenhaeuser/st-elisabeth-mayen/ueberblick/ merged, seems to be mixed up with IK 260711669 and 260710010
# 260720502 closed by now, seems to have phased out after merge https://www.volksfreund.de/region/rheinland-pfalz/trierer-mutterhaus-uebernimmt-oekumenisches-verbundkrankenhaus_aid-5210492
# 260720502 closed by now, seems to have phased out after merge https://www.volksfreund.de/region/rheinland-pfalz/trierer-mutterhaus-uebernimmt-oekumenisches-verbundkrankenhaus_aid-5210492
# 260720502 closed by now, seems to have phased out after merge https://www.volksfreund.de/region/rheinland-pfalz/trierer-mutterhaus-uebernimmt-oekumenisches-verbundkrankenhaus_aid-5210492
# 260730354 closed

# 260812148 still exists, is part of a different hopsital with IK 260811546 https://www.klinik-ellwangen.de/medizin/kinder-und-jugendpsychiatrie-psychotherapie-und-psychosomatik/kontakt
# 260820035 still open subsequent years IK 260820013 Standort 03
# 260820046 bit unclear, seems to be merged and subsequently closed in 2015 
# 260820273 continued subsequently under 260820284 for some years, still exists, might be part of university hospital Heidelberg by now  https://www.rkh-gesundheit.de/kliniken-zentren/unsere-kliniken/rechbergklinik-bretten/
# 260833110 still exists, might be part of university hospital Freiburg https://www.ukf-reha.de/
# 260833508 closed in 2021 https://bnn.de/mittelbaden/ortenau/oberkirch-krankenhaus-schliessung-september-klinikreform-renchtal
# 260912742 closed in 2016 https://www.kreisbote.de/lokales/weilheim-schongau/peissenberger-krankenhaus-5562613.html
# 260920708 seems to be closed, unclear when that happened
# 260930378 only 2015 is missing
# 260940553 still open https://www.bezirk-oberfranken.de/gesundheit/gesundheitseinrichtungen-des-bezirks-oberfranken-gebo/bezirksklinik-hochstadt

# 260950237 still exists, subsequent years 260950011
# 260950237 still exists, subsequent years 260950011
# 260950237 still exists, subsequent years 260950011
# 260970366 still exists, subsequent merge and IK change to IK 260970366 and IK 260972233 
# 260970366 still exists, subsequent merge and IK change to IK 260970366 and IK 260972233 
# 260970366 still exists, subsequent merge and IK change to IK 260970366 and IK 260972233 
# 260970366 still exists, subsequent merge and IK change to IK 260970366 and IK 260972233 
# 261100310 still exists, only 2015 is missing
# 261100720 seems to be 261102436 now
# 262101312 seems to still exist, other years have 261201312, however a lot of double entries for IK 261201312

# 261401278 seems to still exists after merge(?) with IK 261400040 + Adresse "Plittstraße, 24, 02906, Niesky"
# 269723092 still exists: https://www.rehaklinik-odt.de/startseite/
# 510574479 data for 2016 exists, thus 2015 tba
# 510654114 closed. moved to a different location, only Tagespflege left
# 512106842 still exists, only 2015 is missing

## 260102069, 260320860, 260321532, 260330474, 260531251, 260590231, 260593461, 260641642, 260720502, 260730354, 260820046, 260833508, 260912742, 260920708, 510654114
```

```{r review IKs for last appearances, 2014 manual check hospitals for closures}
IK_closed_hospitals_2014 <- c(260102069, 260320860, 260321532, 260330474, 260531251, 260590231, 260593461, 260641642, 260720502, 260730354, 260820046, 260833508, 260912742, 260920708, 510654114)


df_closed_hospitals_2014 <- df_last_in_2014 %>%
  filter(IK_Institutionskennzeichen %in% IK_closed_hospitals_2014) %>%
  mutate(across(everything(), as.character))
```

```{r review IKs for last appearances, 2015 (compared to 2016/2017) manual check hospitals for closures}
df_last_in_2015_20162017 %>%
  distinct(IK_Institutionskennzeichen) %>%
  nrow()


# 360310107 exists for the other years under IK 260310107
# 260310232 closed by the end of 2016 https://www.kma-online.de/aktuelles/klinik-news/detail/krankenhaus-st-vinzenz-braunschweig-schliesst-frueher-a-33268
# 260310517 closed, probably by 2016 at the latest: https://www.hna.de/lokales/hann-muenden/umbau-ehemaligen-krankenhauses-zum-fluechtlingsheim-in-hann-muenden-8334475.html
# 260320940 still open https://eilenriedeklinik.de/
# 260321020 exists, but seems to be part of 260300070 by now also officially https://www.khmue.de/medizin/nephrologie/
# 260321199 still exists https://dsk-bm.de/
# 260330613 closed in 2017 https://www.ms.niedersachsen.de/startseite/uber_uns/presse/presseinformationen/erstes-sonderinvestitionsprogramm-fuer-niedersachsens-krankenhaeuser-beschlossen--mit-13-milliarden-euro-wird-der-sanierungsstau-mageblich-abgebaut-151442.html
# 290510029 still exists https://www.sana.de/duesseldorf-gerresheim/medizin-pflege#tab-31985
# 260510564 still exists, data is incomplete but but at least more complete when combining 260510575 and 260510564 (standort for both 2)
# 260513271 still exists on this address, https://www.schoen-klinik.de/duesseldorf, change of ownership, combine 260510063, 260513271, 260500254

# 260530922 still exists https://www.kkhm.de/einrichtungen/krankenhaus-schleiden/anfahrt-und-kontakt, being one of two hospitals, later under IK 260530900: https://www.kkhm.de/ueber-uns/qualitaet#c1563
# 260531002 closed https://rp-online.de/nrw/staedte/wegberg/aus-fuer-krankenhaus-in-wegberg_aid-21146169
# 260531146 still exists https://www.klinikum-oberberg.de/kontakt, overlap with IK 260531046
# 260531375 still exists https://kliniken-troisdorf.gfo-online.de/ with another "Hospital" for all years (IK 260531364), only for the last two years again distinct (still IK 260531364) 
# 260550938 still exists, part of uniklinik: https://ukm-mhs.de/, since 2016 as IK 260500221
# 260550938 still exists, part of uniklinik: https://ukm-mhs.de/, since 2016 as IK 260500221
# 260550938 still exists, part of uniklinik: https://ukm-mhs.de/, since 2016 as IK 260500221
# 260550938 still exists, part of uniklinik: https://ukm-mhs.de/, since 2016 as IK 260500221
# 260551052 still exists, https://www.marienhospital-oelde.de/mh/index.php, mixed with another hopsital and IK 260571421, 260570124
# 260593713 also under IK 260592723 for 2012,  still exists and existed since 2005 https://www.fliedner.de/de/seelische_gesundheit/fliedner_klinik_gevelsberg/fliedner_klinik_gevelsberg.php

# 260610576 still exists https://www.hgh-bensheim.de/
# 260610612 still exists https://www.stmarienkrankenhaus.de/, now IK 260600266
# 260610725 still exists https://www.lukas-gesellschaft.de/startseite-st-rochus-hospital.html
# 260611407 closed in 2017: https://www.kma-online.de/aktuelles/klinik-news/detail/marienkrankenhaus-floersheim-schliesst-ende-september-a-34842
# 260611613 still exists https://www.helios-gesundheit.de/standorte-angebote/kliniken/idstein/
# 260611264 still exists https://www.vitos.de/gesellschaften/vitos-rheingau/ seems to be for other years IK 260611624
# 260710851 still exists https://www.drk-kamillus-klinik.de/ab/index.php now IK 260712012
# 260711077 still exists: https://www.st-vincenz.de/einrichtungen/krankenhaus-diez subequently IK 260700041
# 260731219 is closed closed since 2020: https://www.swr.de/swraktuell/rheinland-pfalz/mainz/fluechtlinge-kommen-in-ehemaligem-krankenhaus-in-ingelheim-unter-100.html "das Krankenhaus in Ingelheim hat 2020 den Betrieb eingestellt". FROM 2008 til 2015 as 260730708 and 260731219 continued to exist for other years under IK 260700143 260730708
# 260820397 still exists https://www.klinikum-mittelbaden.de/, changed to 260820433

# 260911068 still exists https://www.kliniken-suedostbayern.de/de/leistung/fachklinik-berchtesgaden.htm
# 260912252 https://www.merkur.de/lokales/starnberg/seit-schliessung-schoen-klinik-wird-es-eng-im-klinikum-starnberg-7411917.html closed in 2016: vor allem die Schließung der Schön-Klinik, die für zusätzlichen Andrang sorgt
# 260914642 closed, moved to "neuen Standort in der Kreisklinik Trostberg" : https://www.kliniken-suedostbayern.de/de/leistung/schmerzzentrum-ruhpolding.htm
# 260920207 still open, https://www.donau-isar-klinikum.de/unser-klinikum/standort-landau/index.html since merge IK 260920127 shared with another location without distinction
# 260930312 closed since early 2020 https://www.aerzteblatt.de/nachrichten/108703/Krankenhaus-in-Parsberg-schliesst-vorzeitig since 2016 260930301 https://www.klinikum-neumarkt.de/240-Startseite.html
# 960230378 all other years have 260930378, still exists: https://www.medbo.de/kliniken-einrichtungen/psychiatrie-psychotherapie/klinik-fuer-psychiatrie-psychosomatik-psychotherapie-woellershof
# 261100320 all other years have 261100310, still exists: https://www.johannesstift-diakonie.de/index.php?id=25 
# 261102367 still exists, https://www.doctolib.de/klinik/berlin/poliklin-diabetesklinik-diabetes-spezialklinik 2009 IK 261101925 
# 261600974 unclear, no info other than a mention in 2020 of a "stationäre Pflegeeinrichtung"... disregard since not mentioned anylonger
# 519106622  still open https://www.bruecke-sh.de/wo-wir-unterstuetzen/kreis-ploen/psychiatrische-tagesklinik-preetz/ for all year except 2015 510106622, for 2015 510106622 instead of "Psychiatrische Tagesklinik Preetz" is "Psychiatrische Tagesklinik Plön" with a different address 

# 510571498 seems to be closed, existed since 1994 https://www.privatklinik-portal.de/privatkliniken/klinik-fuer-venenchirurgie/
# 570320085 still exists,first year under IK 260321042 and 260321235 (then sold from private to private to Helios, now "vamed") 

## 260310232, 260310517, 260330613, 260531002, 260611407, 260731219, 260912252, 260930312, 261600974, 510571498
```

```{r review IKs for last appearances, 2015 manual check hospitals for closures}
IK_closed_hospitals_2015 <- c(260310232, 260310517, 260330613, 260531002, 260611407, 260731219, 260912252, 260930312, 261600974, 510571498)


df_closed_hospitals_2015 <- df_last_in_2015_20162017 %>%
  filter(IK_Institutionskennzeichen %in% IK_closed_hospitals_2015) %>%
  mutate(across(everything(), as.character))
```

```{r review IKs for last appearances, 2017 manual check hospitals for closures}
df_last_in_2017 %>%
  distinct(IK_Institutionskennzeichen) %>%
  nrow()

# 260100717 still exists, IK 260100626 for all years
# 260102354 still exists, IK 260102343 for all years
# 260102537 still exists, only 2018 misses
# 260320278 does not exist anymore, closed in 2018 https://de.wikipedia.org/wiki/Helios_Klinikum_Hildesheim "Im September 2018 wurde die Helios Lungenklinik Diekholzen am Standort Diekholzen geschlossen und in das Helios Klinikum Hildesheim integriert"
# 260320370 still exists
# 260321725 closed in 2017 for merge with other hospitals https://de.wikipedia.org/wiki/Agaplesion_Ev._Krankenhaus_Bethel_B%C3%BCckeburg#cite_ref-2 "Der Landkreis Schaumburg setzte eine Neugestaltung der Krankenhausversorgung im Landkreis um. Alle drei Krankenhäuser im Schaumburger Land, neben dem Krankenhaus Bethel waren das die beiden im Agaplesion Ev. Klinikum Schaumburg zusammengeschlossenen Kreiskrankenhäuser Rinteln und Stadthagen, wurden bis 2017 in einem Krankenhaus zusammengeführt. Ein Neubau mit 437 Betten wurde am Rand von Obernkirchen südlich der Ortschaft Vehlen errichtet."
# 260321747 closed in 2017 for merge with other hospitals https://de.wikipedia.org/wiki/Agaplesion_Ev._Krankenhaus_Bethel_B%C3%BCckeburg#cite_ref-2 "Der Landkreis Schaumburg setzte eine Neugestaltung der Krankenhausversorgung im Landkreis um. Alle drei Krankenhäuser im Schaumburger Land, neben dem Krankenhaus Bethel waren das die beiden im Agaplesion Ev. Klinikum Schaumburg zusammengeschlossenen Kreiskrankenhäuser Rinteln und Stadthagen, wurden bis 2017 in einem Krankenhaus zusammengeführt. Ein Neubau mit 437 Betten wurde am Rand von Obernkirchen südlich der Ortschaft Vehlen errichtet."
# 260321758 closed in 2017 for merge with other hospitals https://de.wikipedia.org/wiki/Agaplesion_Ev._Krankenhaus_Bethel_B%C3%BCckeburg#cite_ref-2 "Der Landkreis Schaumburg setzte eine Neugestaltung der Krankenhausversorgung im Landkreis um. Alle drei Krankenhäuser im Schaumburger Land, neben dem Krankenhaus Bethel waren das die beiden im Agaplesion Ev. Klinikum Schaumburg zusammengeschlossenen Kreiskrankenhäuser Rinteln und Stadthagen, wurden bis 2017 in einem Krankenhaus zusammengeführt. Ein Neubau mit 437 Betten wurde am Rand von Obernkirchen südlich der Ortschaft Vehlen errichtet."
# 260330602 closed by end of 2018: https://www.kma-online.de/aktuelles/klinik-news/detail/martin-luther-krankenhaus-in-zeven-wird-ende-2018-geschlossen-a-37300
# 260400300 still open https://diakonie-bhv.de/unsere-angebote/kinder-und-jugendliche/arche-klinik/arche-klinik-test.html
# 260500221 still open https://ukm-mhs.de/ but confusion over address, should be Mauritiusstr. 5 48565 Steinfurt(?) 
# 260500221 still open https://ukm-mhs.de/ but confusion over address, should be Mauritiusstr. 5 48565 Steinfurt(?)
# 260500221 still open https://ukm-mhs.de/ but confusion over address, should be Mauritiusstr. 5 48565 Steinfurt(?)
# 260500221 still open https://ukm-mhs.de/ but confusion over address, should be Mauritiusstr. 5 48565 Steinfurt(?)
# 260510030 still open https://www.sana.de/duesseldorf-benrath
# 260531148 still open https://kliniken-rhein-berg.gfo-online.de/
# 260531206 still open https://kliniken-bonn.gfo-online.de/
# 260550175 still open https://www.raphaelsklinik.de/
# 260570102 still open https://evkb.de/
# 260570431 still open https://www.median-kliniken.de/de/median-klinik-flachsheide-bad-salzuflen/
# 260590743 still open but merged with another hospital: Die Krankenhäuser in Arnsberg und Meschede arbeiten künftig unter dem Dach einer gemeinsamen Krankenhausgesellschaft zusammen https://www.sauerlandkurier.de/hochsauerlandkreis/meschede/walburga-krankenhaus-meschede-klinikum-arnsberg-besiegeln-allianz-8505933.html
# 260591562 still open https://www.krankenhaus-werne.de/
# 260621216 still open https://www.wicker.de/kliniken/neurologische-akutklinik
# 260640652 still open https://www.emma-klinik.de/
# 260730401 still open, only 2018 is missing
# 260810179 still open, but merge/ownership change in 2023: https://www.sana.de/newsroom/robert-bosch-krankenhaus-uebernimmt-sana-klinik-bethesda/ "Die Robert-Bosch-Krankenhaus GmbH (RBK) übernimmt zum 1. Januar 2023 die Sana Klinik Bethesda Stuttgart gGmbH. Der Standort wird künftig als „Robert-Bosch-Krankenhaus, Standort City“ firmieren und nicht nur die Akutgeriatrie und Geriatrische Rehabilitation sowie die Innere Medizin beherbergen, sondern auch zum 1. März 2023 die Plastische Chirurgie des RBK"
# 260812104 still open https://www.kn-calw.de/
# 260830583 still open, only 2018 is missing
# 260831470 still open, prob ably restructured as part of univeristätsklinik https://www.glkn.de/glkn/standorte/vincentius-krankenhaus-konstanz/vincentius-kn-startseite.php
# 260914083 still open https://kliniken.medicalpark.de/loipl
# 260970629 closed https://www.augsburger-allgemeine.de/illertissen/illertissen-die-illertalklinik-verschwindet-endgueltig-aus-illertissen-id58154416.html
# 260972073 still open https://www.vamed-gesundheit.de/reha/bad-groenenbach/unsere-klinik/qualitaet-und-hygiene/hygienestandards/ansprechpartner/psychosomatik-ansprechpartner/
# 261102436 still open, only 2018 is missing
# 261300481 still open, only 2016, 2018 and 2019 are missing 
# 261300481 still open, only 2016, 2018 and 2019 are missing 
# 261300481 still open, only 2016, 2018 and 2019 are missing 
# 261300481 still open, only 2016, 2018 and 2019 are missing 
# 261300481 still open, only 2016, 2018 and 2019 are missing 
# 261401234 still open https://www.klinikum-dresden.de/
# 261450085 still open https://www.klinik-am-brunnenberg.de/unsere-klinik/ueber-unsere-klinik/
# 269726028 still open, data exists for for 2015, 2017, 2019 https://www.deutsche-rentenversicherung.de/SharedDocs/Standorte/Reha-Kliniken/Traeger/Nord/Rehazentrum-Aukrug.html
# 510335903 still open https://www.median-kliniken.de/de/median-klinik-gyhum/
# 510556956 still open https://www.wa.de/lokales/drensteinfurt/sind-im-dorf-angekommen-92305549.html
# 510571205 no info found, probably closed
# 510571205 no info found, probably closed
# 510571205 no info found, probably closed

## 260320278, 260321725, 260321747, 260321758, 260330602, 260970629, 510571205
```

```{r review IKs for last appearances, 2017 manual check hospitals for closures}
IK_closed_hospitals_2017 <- c(260320278, 260321725, 260321747, 260321758, 260330602, 260970629, 510571205)

df_closed_hospitals_2017 <- df_last_in_2017 %>%
  filter(IK_Institutionskennzeichen %in% IK_closed_hospitals_2017) %>%
  mutate(across(everything(), as.character))
```

```{r review IKs for last appearances, 2018 manual check hospitals for closures}
df_last_in_2018 %>%
  distinct(IK_Institutionskennzeichen) %>%
  nrow()

# 260100089 still open, subsequent years as IK 260102434
# 260100329 closed https://www.kn-online.de/lokales/neumuenster/klinik-dr-lehmann-schliesst-DFAZ2MYL5BAKLV2AIBUJKOIP6E.html
# 260102069 still open https://de.wikipedia.org/wiki/Diakonissenkrankenhaus_Flensburg, IK on this address: 260100023, 510112094, 510112107
# 260510289 still open: https://www.kma-online.de/aktuelles/klinik-news/detail/gfo-sichert-sich-mehrheit-am-moers-verbund-47201 https://kliniken-niederrhein.gfo-online.de/medizin-zentren/psychiatrie-psychosomatik-und-psychotherapie/st-camillus
# 260510519 still exists: https://kem-med.com/evang-krankenhaus-essen-werden/
# 260511667 still exists: https://rheinlandklinikum.de/unsere-haeuser
# 260530045 still exists: https://de.wikipedia.org/wiki/Uniklinik_RWTH_Aachen_%E2%80%93_Franziskus
# 260550391 is closed since 2022 https://www.muensterlandzeitung.de/stadtlohn/aus-fuer-stadtlohner-krankenhaus-am-22-oktober-auch-notfallversorgung-endet-w1798660-9000622444/"Aus für Stadtlohner Krankenhaus am 22. Oktober [2022] – auch Notfallversorgung endet"
# 260590208 still exists: https://www.lukas-gesellschaft.de/startseite-st-josefs-hospital.html
# 260593713 also under IK 260592723 for 2012, still exists and existed since 2005 https://www.fliedner.de/de/seelische_gesundheit/fliedner_klinik_gevelsberg/fliedner_klinik_gevelsberg.php
# 260600073 still exists: https://migraene-klinik.de/impressum/
# 260610042 still exists: https://klinikum-darmstadt.de/medizin-pflege/klinik-fuer-psychosomatische-medizin-und-psychotherapie
# 260820898 still exists: https://www.siloah.de/
# 260832701 closed in 2019: "Die Klinik wurde mehr als 26 Jahre erfolgreich als „Michael-Balint-Klinik“ geführt und 2019 geschlossen." https://www.doniswaldklinik.de/geschichte-der-klinik.html on the same location, 2021 a new hospital opened
# 260833494 still exists: https://www.ortenau-klinikum.de/ (klinik wird offenbar mutmasslich 2027 geschlossen), https://www.kehl.de/nachnutzung+krankenhaus
# 260840983 closed, but Stationär until 2021: https://www.regio-tv.de/mediathek/video/krankenhaus-14-nothelfer-steht-kurz-vor-dem-aus/ "Das Krankenhaus 14 Nothelfer in Weingarten steht vor dem Aus. Der Klinikverbund Medizin Campus Bodensee will alle wichtigen Abteilungen am Weingartener Standort schließen. In zwei Jahren werden dort die Patienten nur noch ambulant behandelt."
# 260910169 still open https://kbo-iak.de/standorte/kbo-klinik-fuer-psychiatrie-und-psychotherapie-haar-atriumhaus
# 260912081 new bigger building in the same city (since 2020, IK 772484000), old building seems to be given up: https://www.ovb-online.de/rosenheim/bad-aibling/harthausen-200-eigentumswohnungen-aiblinger-modell-90914910.html
# 260913059 still exists: https://www.sana.de/muenchen
# 260950124 still exists: https://www.klinik-hallerwiese.de/de/klinik-hallerwiese-cnopfsche-kinderklinik.html additional IKs, later: 260950135 260900338 
# 260950135 still exists: https://www.klinik-hallerwiese.de/de/klinik-hallerwiese-cnopfsche-kinderklinik.html additional IKs, later: 260900338 260950124
# 260950965 closed in 2020: "Die Schön Klinik Nürnberg Fürth wird zum 31. Oktober 2020 den Klinikbetrieb einstellen." https://www.schoen-klinik.de/presse/pressemitteilung/8354
# 260960683 still open: https://www.rhoen-klinikum-ag.com/kliniken.html
# 260960923 still open: https://www.campus-nes.de/medizin-pflege/unsere-kliniken.html, later IK 260900407 for "RHÖN-KLINIKUM Campus Bad Neustadt"
# 260961105 still open: 260960923 still open: https://www.campus-nes.de/medizin-pflege/unsere-kliniken.html, later IK 260900407 for "RHÖN-KLINIKUM Campus Bad Neustadt"
# 260961207 still open: 260960923 still open: https://www.campus-nes.de/medizin-pflege/unsere-kliniken.html, later IK 260900407 for "RHÖN-KLINIKUM Campus Bad Neustadt"
# 260970709 still exists https://klinikverbund-allgaeu.de/standorte/kliniken/klinik-immenstadt
# 260970709 still exists https://klinikverbund-allgaeu.de/standorte/kliniken/klinik-immenstadt
# 260970709 still exists https://klinikverbund-allgaeu.de/standorte/kliniken/klinik-immenstadt
# 260970709 still exists https://klinikverbund-allgaeu.de/standorte/kliniken/klinik-immenstadt
# 510962093 still exists but is part of another hospital apparently https://www.bezirkskrankenhaus-lohr.de/unsere-einrichtung/unsere-auenstellen/standort-aschaffenburg/23029.Psychiatrische-Tagesklinik-Am-Rosensee-Aschaffenburg.html

## 260100329, 260550391, 260832701, 260840983, 260912081, 260950965


```

```{r review IKs for last appearances, 2018 manual check hospitals for closures}
IK_closed_hospitals_2018 <- c(260100329, 260550391, 260832701, 260840983, 260912081, 260950965)

df_closed_hospitals_2018 <- df_last_in_2018 %>%
  filter(IK_Institutionskennzeichen %in% IK_closed_hospitals_2018) %>%
  mutate(across(everything(), as.character))
```


```{r review IKs for last appearances, 2019 manual check hospitals for closures}
df_last_in_2019 %>%
  distinct(IK_Institutionskennzeichen) %>%
  nrow()

# 260101525 still exists: https://curschmannklinik.de/Unsere_Klinik/
# 260201025 still exists: https://www.martini-klinik.de/klinik , potetniell teil des Universitätsklinikums Hamburg-Eppendorf mit IK 260200013
# 260330327 is closed by end of 2021: https://www.landeszeitung.de/lokales/lueneburg-lk/lueneburg/lueneburg-die-klinik-havemann-schliesst-UEGSGPVJXCD4OPEY2KVC7IVHPK.html
# 260340454 is closed accoring to maps, no news articles found
# 260511382 still exists: https://www.alexianer-krefeld.de/einrichtungen/krankenhaus-maria-hilf-krefeld
# 260550643 still exists: https://www.hertener-allgemeine.de/herten/25-millionen-euro-operationen-st-elisabeth-hospital-zukunft-pflegeschule-proselis-w856972-8000592028/
# 260550881 first downgrade, https://www.wn.de/muensterland/kreis-steinfurt/ochtrup/pius-hospital-wird-zum-pius-stift-994773?&npg            now it is closed https://www.mathias-stiftung.de/neuigkeiten/neuigkeiten-aus-unseren-leistungsbereichen/schliessung-der-kurzzeitpflegeeinrichtung-im-pius-stift-ochtrup
# 260571820 still exists: https://www.median-kliniken.de/de/median-klinik-am-burggraben-bad-salzuflen/
# 260590561 still exists, https://www.median-kliniken.de/de/median-klinik-am-burggraben-bad-salzuflen/ and for more than the two years with data available: https://www.lz.de/lippe/bad_salzuflen/11202111_Ein-Reha-Aufenthalt-wie-im-Hotel.html
# 260590936 closed 2019: https://www.maerkische-kliniken.de/schliessung-marienhospital-letmathe.html "das Marienhospital hat zum 1. November 2019 seinen Krankenhausbetrieb eingestellt."
# 260591540 still exists merged with another hospital in 2020, now Christliches Klinikum Unna gGmbH with IK 260591539 and Standort-ID 773210000: "Mit der Fusion im Jahr 2020 verschmolzen das Katharinen-Hospital Unna und das Evangelische Krankenhaus Unna zum Christliche Klinikum Unna (CKU). Der neue gemeinsame Name spiegelt die christliche Tradition, sich für das Wohlergehen des Nächsten einzusetzen, wider."
# 260640060 seems to be closed after plans of the local government to move it into the main uni-hospital buildings  https://www.fnp.de/frankfurt/orthopaedie-integrieren-friedrichsheim-soll-uniklinik-11701728.html now it is just indicated as "Amublanz": https://unfallchirurgie-orthopaedie-frankfurt.de/fuer-patienten/ambulante-sprechstunden.html
# 260641619 still open, only 2020 is missing
# 260700143 closed since 2020: https://www.swr.de/swraktuell/rheinland-pfalz/mainz/fluechtlinge-kommen-in-ehemaligem-krankenhaus-in-ingelheim-unter-100.html "das Krankenhaus in Ingelheim hat 2020 den Betrieb eingestellt". FROM 2008 til 2015 as 260730708 and 260731219
# 260710134 still open, only 2020 and 2021 missing
# 260710975 open only as Tagesklinik https://www.loreley-tagesklinik.de/unsere-tagesklinik/, "Loreley-Kliniken schließen Ende September [2020]" https://www.aerzteblatt.de/nachrichten/111897/Loreley-Kliniken-schliessen-Ende-September
# 260710975 open only as Tagesklinik https://www.loreley-tagesklinik.de/unsere-tagesklinik/, "Loreley-Kliniken schließen Ende September [2020]" https://www.aerzteblatt.de/nachrichten/111897/Loreley-Kliniken-schliessen-Ende-September
# 260710975 open only as Tagesklinik https://www.loreley-tagesklinik.de/unsere-tagesklinik/, "Loreley-Kliniken schließen Ende September [2020]" https://www.aerzteblatt.de/nachrichten/111897/Loreley-Kliniken-schliessen-Ende-September
# 260711102 still open: https://www.fachklinik-katzenelnbogen.de/
# 260711497 still open, only 2020 and 2021 missing
# 260820148 still open, but part of another hospital now: https://www.vidia-kliniken.de/standorte#c19824
# 260831891 still open, but new address and name, only for 2020 missing data: https://www.lungenklinik-breisgau.de/
# 260832789 closed in 2021: https://www.bo.de/lokales/kinzigtal/neue-richtlinie-bringt-der-fachklinik-wittichen-das-aus# "Die Fachklinik Wittichen ist seit August [2021] geschlossen"
# 260911262 still open, only 2020 missing
# 261000206 closed in 2020: https://www.saarbruecker-zeitung.de/saarland/landespolitik/marienhaus-schliesst-krankenhaus-losheim-und-plant-tagesklinik_aid-54967187 "Nur noch Tagesklinik in Losheim. Marienhaus lässt vom alten Krankenhaus kaum noch etwas übrig."
# 261000262 closed in 2020: https://www.saarbruecker-zeitung.de/saarland/neunkirchen/ottweiler/die-ehemalige-ottweiler-marienhausklinik-soll-ein-op-zentrum-beherbergen_aid-56653177 "In der geschlossenen Ottweiler Marienhausklinik besteht neben Verwaltungsbetrieb noch ein OP-Zentrum"
# 261102118 still open, only 2020 missing
# 261200377 still open https://www.diakonissenhaus.de/klinik-fuer-geriatrische-rehabilitation
# 261500085 closed in 2020 https://kmg-kliniken.de/akutkliniken/kmg-klinikum-havelberg "Das KMG Klinikum Havelberg hat mit Ablauf des 31. August 2020 seinen Betrieb eingestellt." 
# 261510043 merged with another hopsital, that takes over hospital duties: "der Krankenhausbetrieb des Diakonissenkrankenhauses Dessau zukünftig durch das Städtische Klinikum Dessau fortgeführt werden"
# 269726028 still open https://www.deutsche-rentenversicherung.de/SharedDocs/Standorte/Reha-Kliniken/Traeger/Nord/Rehazentrum-Aukrug.html
# 510106995 still open https://de.wikipedia.org/wiki/Diakonissenkrankenhaus_Flensburg, IK on this address: 260100023, 510112094, 510112107
# 510204927 still open: https://www.tagesklinik-uhlenhorst.de/ IK 260200273 Standort 05(?)
# 510818532 still open: https://www.kn-calw.de/tagesklinik-fuer-kinder-jugendpsychiatrie-psychotherapie-boeblingen

## 260330327, 260340454, 260550881, 260590936, 260640060, 260700143, 260832789, 261000206, 261000262, 261500085, 261510043
```

```{r review IKs for last appearances, 2019 manual check hospitals for closures}
IK_closed_hospitals_2019 <- c(260330327, 260340454, 260550881, 260590936, 260640060, 260700143, 260832789, 261000206, 261000262, 261500085, 261510043)

df_closed_hospitals_2019 <- df_last_in_2019 %>%
  filter(IK_Institutionskennzeichen %in% IK_closed_hospitals_2019) %>%
  mutate(across(everything(), as.character))
```

```{r review IKs for last appearances, 2020 manual check hospitals for closures}
df_last_in_2020 %>%
  distinct(IK_Institutionskennzeichen) %>%
  nrow()

## erste Seite
# 260101079 is actually closed https://fz-borstel.de/index.php/de/sitemap/mediaservices/pressemitteilungen/2021 "Schließung der Medizinischen Klinik 20.12.2021 Aufgrund gesundheitswirtschaftlicher Gründe, die es nicht mehr erlauben, eine Klinik dieser Größe zu betreiben, schließt die Medizinische Klinik Borstel endgültig zum 31. Dezember dieses Jahres.
# 260330190 still exists,	all other years except 2021 contain info, thus error in the data
# 260511907 seems to still exist: https://ptv-solingen.de/behandlung/tagesklinik/
# 260531592 seems to still exist https://www.tagesklinik-pionierstrasse.de/
# 260550244 seems to still exist https://www.klinikum-westmuensterland.de/st-marien-krankenhaus-ahaus/
# 260550244 seems to still exist https://www.klinikum-westmuensterland.de/st-marien-krankenhaus-ahaus/
# 260550244 seems to still exist https://www.klinikum-westmuensterland.de/st-marien-krankenhaus-ahaus/
# 260550266 seems to still exist https://www.klinikum-westmuensterland.de/st-agnes-hospital-bocholt/
# 260550266 seems to still exist https://www.klinikum-westmuensterland.de/st-agnes-hospital-bocholt/
# 260550507 seems to be 260501632 now

## zweite Seite 
# 260593724 merged in 2021, by now this branch is closed https://klinik-volmarstein.de/  https://www.wp.de/staedte/herdecke-wetter/article237618029/Stiftung-Volmarstein-schliesst-die-Ortho-Klinik-in-Dortmund.html
# 260810681 is closed https://www.lkz.de/lokales/landkreis-ludwigsburg_artikel,-altes-marbacher-krankenhaus-ein-gluecksfall-fuer-den-landkreis-ludwigsburg-_arid,683225.html
# 260822220 is closed https://kreis-calw.de/Der-Landkreis/Pressemitteilungen/Sana-Klinik-Bad-Wildbad-stellt-Betrieb-ein.php?object=tx,2442.14.1&ModID=7&FID=2442.14689.1&NavID=2442.562&La=1 "Die Sana Klinik Bad Wildbad stellt den ambulanten und stationären Versorgungsbetrieb am 31. Juli [2022] ein."
# 260833450 existiert, ist mutmasslich organisatorisch in Uniklinik eingegliedert: https://www.uniklinik-freiburg.de/so-finden-sie-uns/lageplaene.html 
# 260833450 existiert, ist mutmasslich organisatorisch in Uniklinik eingegliedert: https://www.uniklinik-freiburg.de/so-finden-sie-uns/lageplaene.html 
# 260840471 is closed https://de.wikipedia.org/wiki/Fachklinik_f%C3%BCr_Neurologie_Dietenbronn "Zum Jahresende 2021 wurde der Standort geschlossen und in die Sana Klinik Biberach eingegliedert."
# 260930130 still exists, since 2021 "260930163", merged with another hospital "St. Anna Krankenhaus" https://www.kh-as.de/medizin-pflege/
# 260930323 is closed https://www.medbo.de/unternehmen/medbo-einblicke/medbo-neuigkeiten/neuigkeiten-detail/ende-und-neuanfang

## 260101079, 260593724, 260810681, 260822220, 260840471, 260930323
```

```{r review IKs for last appearances, 2020 manual check hospitals for closures}
IK_closed_hospitals_2020 <- c(260101079, 260593724, 260810681, 260822220, 260840471, 260930323)


#Filter the dataset for closed hospitals and convert all columns to character
df_closed_hospitals_2020 <- df_last_in_2020 %>%
  filter(IK_Institutionskennzeichen %in% IK_closed_hospitals_2020) %>%
  mutate(across(everything(), as.character))
```


```{r review IKs for last appearances, 2021 manual check hospitals for closures}
df_last_in_2021 %>%
  distinct(IK_Institutionskennzeichen) %>%
  nrow()

## erste Seite
# 260100318 seems to still exist: https://www.drk-nms.de/psychiatrisches-behandlungszentrum.html
# 260102582 seems to still exist:  https://www.tagesklinik-nms.de/
# 260200581 seems to still exist:  https://www.tk-pia-praxisklinik.de/de/
# 260200990 seems to still exist:  https://www.uke.de/kliniken-institute/zentren/universit%C3%A4res-herzzentrum-(uhz)/index.html
# 260310323 is actually closed: https://www.asklepios.com/clausthal-zellerfeld/ 
# 260330680 seems to still exist:  https://www.orthoklinik-lueneburg.de/patienten-besucher/die-orthoklinik
# 260330715 seems to close: https://www.kreiszeitung-wochenblatt.de/stade/c-wirtschaft/endgueltiges-aus-fuer-die-klinik-dr-witwity-in-stade_a301237 
# 260330851 is actually closed:  https://www.cnv-medien.de/stadt-cuxhaven/altes-helios-seehospital-in-sahlenburg-verkommt-zusehends.html "Ende 2021 schloss das Helios-Seehospital seine Türen."
# 260340795 is actually closed:  https://www.noz.de/lokales/osnabrueck/artikel/ex-paracelsus-klinik-in-osnabrueck-wird-ende-2024-ausgeraeumt-47267929 
# 260400300 seems to still exist: https://diakonie-bhv.de/unsere-angebote/kinder-und-jugendliche/arche-klinik/arche-klinik-test.html

## zweite Seite
# 260500470		17-21 liegt vor, Bericht von 2022 sagt die Klinik wird geschlossen: https://www.radiomk.de/artikel/aus-fuer-das-bethanien-nur-noch-ein-krankenhaus-fuer-iserlohn-1507224.html Aber noch 2024 offen: https://www.ikz-online.de/staedte/iserlohn/article241803670/Iserlohn-fuer-Herzpatienten-jetzt-doppelt-gut-aufgestellt.html. Lage unklar. Wird wohl geschlossen? Inhaberwechsel fand statt
# 260500492	seems to still exist: https://www.tk-lemgo.de/	eröffnet 2017, aber "Seit Oktober 2017 werden in der Tagesklinik für Psychiatrie und Psychosomatik Patient*innen erfolgreich behandelt."
# 260511188	seems to still exist: https://www.fliedner.de/de/seelische_gesundheit/fliedner_krankenhaus_ratingen/fliedner_krankenhaus_ratingen.php 
# 260512112	seems to still exist:	https://luisenkrankenhaus.de/unser-haus/ 14-21 liegt vor, Klinik ist älter: "Seit 1997 steht das Luisenkrankenhaus in Düsseldorf für professionelle Medizin und intensive Pflege."
# 260530728	is actually closed, but in 2023:	https://www1.wdr.de/nachrichten/rheinland/Linnich-kritisiert-Krankenhaus-Schliessung-100.html
# 260530773	no indication of a hospital closure: https://www.dicvfreiburg.caritas.de/adressen/marien-hospital-erftstadt/50374-erftstadt/99285
# 260550153	seems to still exist: https://www.hjk-muenster.de/unsere-kompetenzen/uebersicht-der-medizinischen-fachabteilungen.html
# 260570124	still exists, but changed ownership-structure, IK now seems to be 260571421, merged with pre-existing other hospitals	
# 260570124	still exists, but changed ownership-structure, IK now seems to be 260571421, merged with pre-existing other hospitals
# 260570124 still exists, but changed ownership-structure, IK now seems to be 260571421, merged with pre-existing other hospitals

## dritte Seite
# 260590059 is actually closed, https://www.bochum.de/Pressemeldungen/3-April-2023/Entwicklung-des-ehemaligen-St.-Josef-Hospital-Gelaendes-in-Linden
# 260590128	still exists	https://www.klinikum-bochum.de/standorte/martin-luther-krankenhaus-wattenscheid.html
# 260591528		still exists https://www.marien-kh.de/ IK 260591517 seems to existed at the same time, for 2022 only one remains? both have different addresses, both still exist
# 260660668	still exists https://www.orthopaedie-badhersfeld.de/, might be part of a different hospital(?)
# 260710635	still exists: https://www.e-s-b.org/krankenhaus/
# 260711260	closed in 2023: https://www.swr.de/swraktuell/rheinland-pfalz/koblenz/bad-ems-paracelsus-klinik-ist-jetzt-dicht-100.html
# 260730593	merged with another hospital, still exists, now IK 260730263: "Zum 1. Januar 2022 haben das Städtische Krankenhaus Pirmasens und das St. Elisabeth Krankenhaus Rodalben fusioniert. Wir gehören zusammen!"
# 260820514 still exists: https://www.sankt-elisabeth.de/info-center/klinik/
# 260830867 still exists: https://www.median-kliniken.de/de/median-franz-alexander-klinik-nordrach/
# 260831185 still exists: https://www.median-kliniken.de/de/median-klinik-st-georg-bad-duerrheim/

## vierte Seite
# 260831620 still exists: https://www.klinloe.de/patienten-und-besucher/kontakt-anfahrt.html
# 260831620 still exists: https://www.klinloe.de/patienten-und-besucher/kontakt-anfahrt.html
# 260831620 still exists: https://www.klinloe.de/patienten-und-besucher/kontakt-anfahrt.html
# 260900167 still exists: https://www.barmherzige-regensburg.de/unser-haus/historie/paul-gerhardt-haus.html opened in 2017, same address like hospital IK 260930050
# 260911707 still exists https://www.innklinikum.de/medizin-standorte/klinikstandorte
# 260911707 still exists https://www.innklinikum.de/medizin-standorte/klinikstandorte
# 260912230 still exists: https://www.merkur.de/lokales/starnberg/kreisbote/neue-aera-an-der-schindlbeck-klinik-in-herrsching-beginnt-92808276.html
# 260913399	still exists https://www.ms-klinik.de/
# 260913550	closed in 2023 https://www.pnp.de/lokales/landkreis-berchtesgadener-land/schlossklinik-abtsee-psyche-im-fokus-aber-auf-keinen-fall-konkurrenz-zur-kbo-14268962
# 260913776 still exists https://kbo-isk.de/

## fünfte Seite 
# 260970355		still exists https://www.khdw.de/medizin-und-pflege/zentrale-interdisziplinaere-notaufnahme-wertingen/
# 260971937		still exists https://www.khdw.de/medizin-und-pflege/zentrale-interdisziplinaere-notaufnahme-dillingen/
# 261100070		still exists https://www.drk-kliniken-berlin.de/mitte/auflistung-kliniken
# 261100387		still exists https://www.drk-kliniken-berlin.de/wiegmann-klinik
# 261101311		still exists https://www.drk-kliniken-berlin.de/koepenick
# 261101561		still exists https://www.drk-kliniken-berlin.de/westend
# 261102118		still exists https://www.augenklinik-ringcenter.de/klinik/
# 261400119		closed in 2023: https://www.reichenbach-vogtland.de/bildung-soziales/gesundheit/krankenhaus/
# 261400836		https://www.heinrich-braun-klinikum.de/standort-zwickau-werdauer-strasse.php "Seit 1. Dezember 2022 gehört die ehemalige Paracelsus-Klinik Zwickau zum Heinrich-Braun-Klinikum gemeinnützige GmbH (HBK)" IK 261400379 (Standortnummer 772531000)
# 261500416 still exists https://www.klinikum-naumburg.de/unser-klinikum/

## sechste Seite 
# 261500416	 still exists https://www.klinikum-zeitz.de/unser-klinikum/	
# 261500483		closed by end of 2023: "Die Lungenklinik Ballenstedt Harz GmbH ist seit dem 01.01.2024 geschlossen!!!" https://www.lk-b.de/startseite.html
# 261600996	still exists https://www.median-kliniken.de/de/median-klinik-bad-tennstedt/	
# 510100374	still exists https://www.vdek-kliniklotse.de/Psychiatrische-Tagesklinik-Heide-Bruecke-Schleswig-Holstein-gGmbH-in-25746-Heide/uebersicht/krankenhaus/51010037400
# 510106622		still exists: https://www.bruecke-sh.de/wo-wir-unterstuetzen/kreis-ploen/psychiatrische-tagesklinik-preetz/
# 511500416		still exists: https://www.neinstedt.de/esn/angebote/gesundheitsangebote/Evangelisches-Fachkrankenhaus-fuer-Psychiatrie-Hildegard-von-Bingen-in-Neinstedt.php
# 512106842 still exists: https://www.bruecke-sh.de/wo-wir-unterstuetzen/kreis-ploen/psychiatrische-tagesklinik-ploen/

## only the following hospitals are actually closed, a lot only by 2023:
## 260310323, 260330715, 260330851, 260340795, 261500483, 260530728, 260590059, 260711260, 260913550, 261400119

```

```{r review IKs for last appearances, 2021 manual check hospitals for closures}
IK_closed_hospitals_2021 <- c(260310323, 260330715, 260330851, 260340795, 261500483, 260530728, 260590059, 260711260, 260913550, 261400119)

#Filter the dataset for closed hospitals and convert all columns to character
df_closed_hospitals_2021 <- df_last_in_2021 %>%
  filter(IK_Institutionskennzeichen %in% IK_closed_hospitals_2021) %>%
  mutate(across(everything(), as.character))
```


```{r merge annual hospital closures into combined dataframe}
# Combine hospital closure datasets from multiple years into a single dataframe
df_hospital_closures_combined <- bind_rows(
  df_closed_hospitals_2008,
  df_closed_hospitals_2010,
  df_closed_hospitals_2012,
  df_closed_hospitals_2013,
  df_closed_hospitals_2014,
  df_closed_hospitals_2015,
  df_closed_hospitals_2017,
  df_closed_hospitals_2018,
  df_closed_hospitals_2019, 
  df_closed_hospitals_2020, 
  df_closed_hospitals_2021
  )

# Ensure consistent data types for key columns
df_hospital_closures_combined$year <- as.factor(df_hospital_closures_combined$year)
df_hospital_location_merged_geocoded$year <- as.factor(df_hospital_location_merged_geocoded$year)
df_hospital_closures_combined$Datum <- as.Date(df_hospital_closures_combined$Datum)
df_hospital_closures_combined$IK_Institutionskennzeichen <- as.double(df_hospital_closures_combined$IK_Institutionskennzeichen)


# Perform a semi-join to keep only closures that match geocoded hospital locations
df_hospital_closures_combined_geocoded <- semi_join(
  df_hospital_location_merged_geocoded, 
  df_hospital_closures_combined, 
  by = c("Name", "Datum", "IK_Institutionskennzeichen", "year")
)

# Print the final geocoded hospital closure dataset
# print(df_hospital_closures_combined_geocoded)
```
df_hospital_closures_combined_geocoded_continue
```{r include manual research on closures from external .txt-file}
# Read the file into a character vector
reasons_raw <- readLines("reasons_file.txt")

# Parse the file into a structured dataframe
reasons_df <- data.frame(
  # Extract hospital identifier (IK_Institutionskennzeichen) after '# '
  IK_Institutionskennzeichen = str_extract(reasons_raw, "(?<=# )\\d+"),  
  
  # Extract closure context information between ';;;' delimiters
  closure_context_info = str_extract(reasons_raw, "(?<=;;;).*?(?=;;;\\s?\\d{4}|;;;\\s?NA)"), 
  
  # Extract the year of closure (last value after ';;;')
  year_of_closure = str_extract(reasons_raw, "(?<=;;;)([^;]+)$"),        
  
  stringsAsFactors = FALSE
) %>%
  # Remove any leading or trailing spaces in the extracted closure year
  mutate(year_of_closure = str_trim(year_of_closure))

# The dataframe 'reasons_df' now contains:
# - IK_Institutionskennzeichen (hospital identifier)
# - closure_context_info (additional information)
# - year_of_closure (closure year or NA if unavailable)

reasons_df <- reasons_df %>%
  mutate(IK_Institutionskennzeichen = as.character(IK_Institutionskennzeichen))

# Merge the extracted reasons data with the existing hospital closures dataset
df_hospital_closures_combined_geocoded <- df_hospital_closures_combined_geocoded %>%
  mutate(IK_Institutionskennzeichen = as.character(IK_Institutionskennzeichen)) %>%
  left_join(reasons_df, by = "IK_Institutionskennzeichen", multiple = "first") %>%
  
  # Convert "NA" strings to actual NA values and transform 'year_of_closure' into a factor
  mutate(
    year_of_closure = na_if(year_of_closure, "NA"), 
    year_of_closure = as.factor(year_of_closure),
    IK_Institutionskennzeichen = as.factor(IK_Institutionskennzeichen)
  )

# The resulting dataframe 'df_hospital_closures_combined_geocoded' now contains:
# - Merged hospital closure records
# - Contextual closure information
# - Standardized closure year as a factor

# The updated dataframe is ready for further analysis or visualization
#df_hospital_closures_combined_geocoded
```

```{r include staff data for info on doctors and surses on the closing hospitals}
# Convert all columns to character type to ensure compatibility across datasets
df_list <- list(
  df_hospital_staff_2008,
  df_hospital_staff_2010,
  df_hospital_staff_2012,
  df_hospital_staff_2013,
  df_hospital_staff_2014,
  df_hospital_staff_2015,
  df_hospital_staff_2016,
  df_hospital_staff_2017,
  df_hospital_staff_2018,
  df_hospital_staff_2019, 
  df_hospital_staff_2020, 
  df_hospital_staff_2021
)

# Apply character conversion to all columns in each dataset
df_staff_list <- lapply(df_list, function(df) {
  df %>% mutate(across(everything(), as.character))
})

# Combine all hospital staff datasets into a single dataframe
df_hospital_closures_staff_geocoded <- bind_rows(df_staff_list) %>%
  
  # Select relevant columns for analysis
  dplyr::select(IK_Institutionskennzeichen, year, Anzahl_Aerzte_VK_ohne_beleg, Anzahl_VK_gesundheits_krankenpfleger) %>%
  
  # Convert hospital identifier to numeric for consistency
  mutate(IK_Institutionskennzeichen = as.factor(IK_Institutionskennzeichen))

# Merge hospital staff data with the geocoded hospital closures dataset
df_hospital_closures_info_combined <- df_hospital_closures_staff_geocoded %>%
  
  # Perform an inner join on hospital identifier and year to link staff data with closure data
  inner_join(
    df_hospital_closures_combined_geocoded,# %>%
      #dplyr::select(IK_Institutionskennzeichen, Standortnummer, year, hospital_index, index, latitude, longitude), 
    by = c("IK_Institutionskennzeichen", "year"),
    multiple = "any"
  ) %>%
  
  # Replace missing values (NA) in the number of doctors column with 0
  mutate(Anzahl_Aerzte_VK_ohne_beleg = ifelse(is.na(Anzahl_Aerzte_VK_ohne_beleg), 0, Anzahl_Aerzte_VK_ohne_beleg)) %>%
  
  # Ensure hospital identifier remains numeric
  mutate(IK_Institutionskennzeichen = as.factor(IK_Institutionskennzeichen)) %>%
  
  # Convert numeric staff-related columns from character (with comma separators) to numeric format
  mutate(
    Anzahl_Aerzte_VK_ohne_beleg = as.numeric(gsub(",", ".", Anzahl_Aerzte_VK_ohne_beleg)),
    Anzahl_VK_gesundheits_krankenpfleger = as.numeric(gsub(",", ".", Anzahl_VK_gesundheits_krankenpfleger)),
    
    # Create a new column summing doctors and nurses to get total hospital staff count
    staff_doctors_nurses_numeric = Anzahl_Aerzte_VK_ohne_beleg + Anzahl_VK_gesundheits_krankenpfleger
  ) %>%
  dplyr::select(
    -"Node1",
    -dplyr::starts_with("POC_")
  )

# Final datasets are available for further analysis
df_hospital_closures_combined_geocoded
df_hospital_closures_info_combined
```
