---
title: "model_basic_SCM"
author: "Niklas Pawelzik"
date: "2024-08-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r import packages}
library(Synth)
library(dplyr)
library(zoo)
library(imputeTS)
library(tidyr)
```

## Creation of the Dataframe for the district with a Hospital Closure

### Level Landkreis

```{r}
# hospital of interest "Springe", PLZ 31832 has NUTS3 "DE929":
df_hospital_location_NUTS3 %>%
  filter(
    str_detect(Adresse, "31832")
  ) %>%
    select(
    NUTS_3_ID
    ) %>%
  unique()

df_NUTS3 %>%
  filter(
    NUTS3 == "DE929"
  )

df_WK_combined_closure <- df_WK_combined %>%
  filter(
    GKZ == "03241000"
  )

# merge based on NUTS3
```

### Level Kommune

```{r}
# hospital of interest "Springe", PLZ 31832 has NUTS3 "DE929", ARS "032410017":
hospitals_with_verwaltungsgemeinschaft %>%
  filter(
    str_detect(Adresse, "31832")
  ) %>%
    select(
    ARS
    ) %>%
  unique()

df_NUTS3 %>%
  filter(
    NUTS3 == "DE929"
  )

df_WK_kommunen_combined <- df_combined_cleaned
df_WK_kommunen_combined$ARS_short <- substr(df_WK_kommunen_combined$ARS, 1, 9)

df_WK_kommunen_combined_closure <- df_WK_kommunen_combined %>%
  filter(
    ARS_short == "032410017"
  )

#03241017

df_WK_kommunen_combined_closure
# merge based on GKZ
```

## Creation of the Dataframe for the districts (assumed to be) without Hospital Closures

### Level Landkreis

```{r}
# closed hospitals:
df_hospital_closures_combined_geocoded_minimum

# NUTS3 for all hospitals:
df_hospital_location_NUTS3

# Perform join to identify NUTS3 for districts with confirmed closures 
df_hospital_closures_combined_geocoded_NUTS3 <- df_hospital_closures_combined_geocoded_minimum %>%
      select(
        -Traegerart
             ) %>%
  inner_join(
    df_hospital_location_NUTS3 %>%
      # include columns NUTS_3_ID and geometry from dataframe df_hospital_location_NUTS3 to add those two columns
      select(year, latitude, longitude, NUTS_3_ID, geometry),
    # match based on year, latitude, longitude to identify districts with confirmed closures
    by = c("year", "latitude", "longitude")
  )

# Print or view the resulting dataframe
print(df_hospital_closures_combined_geocoded_NUTS3)

# column NUTS_3_ID identifies districts that need to be kicked out from donor pool
nuts3_ids_to_remove <- df_hospital_closures_combined_geocoded_NUTS3$NUTS_3_ID
```

```{r}
# hospitals with almost complete data:
df_hospitals_complete_data_distinct

# NUTS3 for all hospitals:
df_hospital_location_NUTS3

# Perform join to identify NUTS3 for districts with confirmed closures 
df_hospitals_complete_data_distinct_NUTS3 <- df_hospitals_complete_data_distinct %>%
#      select( -Traegerart) %>%
  inner_join(
    df_hospital_location_NUTS3 %>%
      # include columns NUTS_3_ID and geometry from dataframe df_hospital_location_NUTS3 to add those two columns
      select(year, latitude, longitude, NUTS_3_ID, geometry),
    # match based on year, latitude, longitude to identify districts with confirmed closures
    by = c("year", "latitude", "longitude")
  )

print(df_hospitals_complete_data_distinct_NUTS3)

# Filter out rows in df_hospitals_complete_data_distinct_NUTS3 with matching NUTS_3_ID
df_hospitals_complete_data_distinct_NUTS3_filtered <- df_hospitals_complete_data_distinct_NUTS3 %>%
  filter(!NUTS_3_ID %in% nuts3_ids_to_remove)

# Print or view the filtered dataframe
print(df_hospitals_complete_data_distinct_NUTS3_filtered)

nuts3_ids_of_donors <- df_hospitals_complete_data_distinct_NUTS3_filtered$NUTS_3_ID
```

```{r}
# Filter for rows in df_NUTS3 with matching NUTS_3_ID
df_NUTS3_donors <- df_NUTS3 %>%
  filter(NUTS3 %in% nuts3_ids_of_donors) %>%
  rename(
    "Schlüsselnummer" = "Schlüssel-nummer"
  ) %>%
  mutate(
    GKZ = paste0(Schlüsselnummer, "000")
    ) %>%
  rename(
    "Schlüssel-nummer" = "Schlüsselnummer"
  )

print(df_NUTS3_donors)

GKZ_of_donors <- df_NUTS3_donors$GKZ

df_WK_combined_donors <- df_WK_combined %>%
  filter(GKZ %in% GKZ_of_donors)
```

### Level Kommune

```{r}
# closed hospitals:
df_hospital_closures_combined_geocoded_minimum

# NUTS3 for all hospitals:
df_hospitals_with_verwaltungsgemeinschaft

# problem can probably be solved by rounding the coordinates on third digit
# Round coordinates to the third decimal place for df_hospital_closures_combined_geocoded_minimum
df_hospital_closures_combined_geocoded_minimum$latitude <- round(df_hospital_closures_combined_geocoded_minimum$latitude, 3)
df_hospital_closures_combined_geocoded_minimum$longitude <- round(df_hospital_closures_combined_geocoded_minimum$longitude, 3)

# Round coordinates to the third decimal place for df_hospitals_with_verwaltungsgemeinschaft
df_hospitals_with_verwaltungsgemeinschaft$latitude <- round(df_hospitals_with_verwaltungsgemeinschaft$latitude, 3)
df_hospitals_with_verwaltungsgemeinschaft$longitude <- round(df_hospitals_with_verwaltungsgemeinschaft$longitude, 3)

# Perform join to identify NUTS3 for districts with confirmed closures 
df_hospital_closures_combined_geocoded_verwaltungsgemeinschaft <- df_hospital_closures_combined_geocoded_minimum %>%
      select(
        -Traegerart
             ) %>%
  inner_join(
    df_hospitals_with_verwaltungsgemeinschaft %>%
      # include columns NUTS_3_ID and geometry from dataframe df_hospital_location_NUTS3 to add those two columns
        select(year, latitude, longitude, ARS, geometry),
    # match based on year, latitude, longitude to identify districts with confirmed closures
    by = c("year", "latitude", "longitude")
  )

# Print or view the resulting dataframe
print(df_hospital_closures_combined_geocoded_verwaltungsgemeinschaft)
print(df_hospital_closures_combined_geocoded_NUTS3)


# column ARS identifies districts that need to be kicked out from donor pool
ARS_to_remove <- df_hospital_closures_combined_geocoded_verwaltungsgemeinschaft$ARS
```

```{r}
# hospitals with almost complete data:
df_hospitals_complete_data_distinct

# ARS for all hospitals:
df_hospitals_with_verwaltungsgemeinschaft

# Round coordinates to the third decimal place for df_hospitals_complete_data_distinct
df_hospitals_complete_data_distinct$latitude <- round(df_hospitals_complete_data_distinct$latitude, 3)
df_hospitals_complete_data_distinct$longitude <- round(df_hospitals_complete_data_distinct$longitude, 3)

# Perform join to identify ARS for districts with confirmed closures 
df_hospitals_complete_data_distinct_verwaltungsgemeinschaft <- df_hospitals_complete_data_distinct %>%
#      select( -Traegerart) %>%
  inner_join(
    df_hospitals_with_verwaltungsgemeinschaft %>%
      # include columns NUTS_3_ID and geometry from dataframe df_hospitals_with_verwaltungsgemeinschaft to add those two columns
      select(year, latitude, longitude, ARS, geometry),
    # match based on year, latitude, longitude to identify districts with confirmed closures
    by = c("year", "latitude", "longitude")
  )

print(df_hospitals_complete_data_distinct_verwaltungsgemeinschaft)

# Filter out rows in df_hospitals_complete_data_distinct_NUTS3 with matching NUTS_3_ID
df_hospitals_complete_data_distinct_verwaltungsgemeinschaft_filtered <- df_hospitals_complete_data_distinct_verwaltungsgemeinschaft %>%
  filter(!ARS %in% ARS_to_remove)

# Print or view the filtered dataframe hospitals with nearly complete data, ARS and coordinates
print(df_hospitals_complete_data_distinct_verwaltungsgemeinschaft_filtered)

ARS_of_donors <- df_hospitals_complete_data_distinct_verwaltungsgemeinschaft_filtered$ARS

print(ARS_of_donors)
```

```{r}
# Print or view the filtered dataframe hospitals with nearly complete data, ARS and coordinates
# needs to be matched with wegweiser_kommune_data
df_WK_kommunen_combined <- df_combined_cleaned
df_WK_kommunen_combined$ARS_short <- substr(df_WK_kommunen_combined$ARS, 1, 9)

print(df_hospitals_complete_data_distinct_verwaltungsgemeinschaft_filtered)

ARS_of_donors <- df_hospitals_complete_data_distinct_verwaltungsgemeinschaft_filtered$ARS

df_WK_kommunen_combined_donors <- df_WK_kommunen_combined %>%
  filter(ARS_short %in% ARS_of_donors)

print(df_WK_kommunen_combined_donors)
```

## Pseudo-Code for the Synthetic Control Method itself

### Landkreislevel

```{r prepare data for scm}
df_WK_combined_donors_closure <- bind_rows(
  df_WK_combined_donors,
  df_WK_combined_closure
)

# Define the treated unit and time periods
  # insert Springe NUTS3 or GKZ as per district_id
treated_unit <- 3241000
  # insert Springe year of hospital closure
treatment_year <- 2014

predictor_variables <- c(
    "Ausbildungsbeginner_innen_mit_Fachhoch_Hochschulabschluss",
    "Kaufkraft_Euro_Haushalt",
    "Wohnfläche_pro_Person_m",
    "Finanzmittelsaldo_Euro_je_Einwohner_in",
    "Steuereinnahmen_pro_Einwohner_in_Euro_je_Einwohner_in",
    "Existenzgründungen_Neuerrichtungen_je_1_000_Einwohner_innen"
)

df_WK_combined_donors_closure[predictor_variables] <- 
  lapply(df_WK_combined_donors_closure[predictor_variables], as.numeric)

df_WK_combined_donors_closure <- df_WK_combined_donors_closure %>%
  group_by(GKZ) %>%  # Group by GKZ
  mutate(across(everything(), ~ ifelse(is.na(.), mean(., na.rm = TRUE), .))) %>%  # Replace NAs with the mean
  ungroup()  # Ungroup the dataframe

target_variable <- c(
  "Beschäftigungsquote"
)

df_WK_combined_donors_closure[predictor_variables] <- 
  lapply(df_WK_combined_donors_closure[predictor_variables], as.numeric)

df_WK_combined_donors_closure$GKZ <- as.numeric(df_WK_combined_donors_closure$GKZ) 
df_WK_combined_donors_closure$year <- as.numeric(df_WK_combined_donors_closure$year) 
GKZ_of_donors <- as.numeric(GKZ_of_donors)

df_WK_combined_donors_closure <- df_WK_combined_donors_closure %>%
  mutate(district_no = as.numeric(factor(GKZ))) %>%
  # randomly decrease donor pool size for now
  filter(
    district_no < 18
  )
```


```{r export dataframe}
file_path_df_WK_combined_donors_closure <- file.path("cleaned_data/df_WK_combined_donors_closure.csv")
write.csv(df_WK_combined_donors_closure, file_path_df_WK_combined_donors_closure, row.names = FALSE)

```

```{r import dataframe}
df_WK_combined_donors_closure_imported <- read_csv(file_path_df_WK_combined_donors_closure)
```


```{r specify parameters for dataprep-function}
df_WK_combined_donors_closure_imported <- as.data.frame(df_WK_combined_donors_closure_imported)

dataprep.out <- dataprep(
  # insert df
  foo = df_WK_combined_donors_closure_imported,
  # insert IVs
  predictors = predictor_variables,
  predictors.op = "mean",
  # insert DV
  dependent = target_variable,
  unit.variable = "district_no",
  time.variable = "year",
  treatment.identifier = 17,
  # Control units (all except the treated one, i.e. Springe - all entries in column except "treated unit")
  controls.identifier = c(1:16),
  # years of Pre-Treatment Period
  time.predictors.prior = 2008:2013,
  # years of Pre-Treatment Period
  time.optimize.ssr = 2008:2013,
  unit.names.variable = "Kommune",
  # complete time period covered, Pre- and Post-Treatment Period
  time.plot = 2008:2020
)

```

```{r run SCM}
synth.out <- synth(dataprep.out)
```


```{r analyze and visualize results}
synth.tables <- synth.tab(dataprep.res = dataprep.out, synth.res = synth.out)

# Plot the results
path.plot(dataprep.res = dataprep.out, synth.res = synth.out, Ylab = "Employment Rate", Xlab = "Year", Main = "SCM for Hospital Closure")
gaps.plot(dataprep.res = dataprep.out, synth.res = synth.out, Ylab = "Gap in Employment Rate", Xlab = "Year", Main = "SCM Gap Plot")

```

### Kommunenlevel

```{r prepare data for scm}
df_WK_kommunen_combined_donors_closure <- bind_rows(
  df_WK_kommunen_combined_donors,
  df_WK_kommunen_combined_closure
)



# Define the treated unit and time periods
  # insert Springe NUTS3 or GKZ or ARS (short) as per district_id
treated_unit <- 032410017
  # insert Springe year of hospital closure
treatment_year <- 2014

numeric_variables <- df_WK_kommunen_combined_donors_closure %>%
  select(
    - Kommune, 
    - GKZ, 
    - ARS, 
    - Bundesland
  ) %>%
  colnames()
  
predictor_variables <- c(
    # "Ausbildungsbeginner_innen_mit_Fachhoch_Hochschulabschluss",
    "Kaufkraft_Euro_Haushalt",
    "Wohnfläche_pro_Person_m",
    "Finanzmittelsaldo_Euro_je_Einwohner_in",
    "Steuereinnahmen_pro_Einwohner_in_Euro_je_Einwohner_in",
    # "Existenzgründungen_Neuerrichtungen_je_1_000_Einwohner_innen",
    "Hochqualifizierte_am_Wohnort"
)

df_WK_kommunen_combined_donors_closure <- df_WK_kommunen_combined_donors_closure %>%
  filter(
    !is.na(year)
  )

df_WK_kommunen_combined_donors_closure[numeric_variables] <- 
  lapply(df_WK_kommunen_combined_donors_closure[numeric_variables], as.numeric)

df_WK_kommunen_combined_donors_closure <- df_WK_kommunen_combined_donors_closure %>%
  group_by(ARS_short) %>%  # Group by ARS
  mutate(across(everything(), ~ ifelse(is.na(.), mean(., na.rm = TRUE), .))) %>%  # Replace NAs with the mean
  ungroup()  # Ungroup the dataframe

target_variable <- c(
  "Beschäftigungsquote_55_bis_64_Jährige"
)

df_WK_kommunen_combined_donors_closure$ARS_short <- as.numeric(df_WK_kommunen_combined_donors_closure$ARS_short) 
df_WK_kommunen_combined_donors_closure$year <- as.numeric(df_WK_kommunen_combined_donors_closure$year) 
ARS_of_donors <- as.numeric(ARS_of_donors)

df_WK_kommunen_combined_donors_closure <- df_WK_kommunen_combined_donors_closure %>%
  mutate(district_no = as.numeric(factor(ARS_short)))
```

```{r specify parameters for dataprep-function}
df_WK_kommunen_combined_donors_closure <- as.data.frame(df_WK_kommunen_combined_donors_closure)

dataprep.out <- dataprep(
  # insert df
  foo = df_WK_kommunen_combined_donors_closure,
  # insert IVs
  predictors = predictor_variables,
  predictors.op = "mean",
  # insert DV
  dependent = target_variable,
  unit.variable = "district_no",
  time.variable = "year",
  treatment.identifier = 34,
  # Control units (all except the treated one, i.e. Springe - all entries in column except "treated unit")
  # randomly decrease donor pool size for now
  controls.identifier = c(1:33, 35:50),
  # years of Pre-Treatment Period
  time.predictors.prior = 2008:2012,
  # years of Pre-Treatment Period
  time.optimize.ssr = 2008:2012,
  unit.names.variable = "Kommune",
  # complete time period covered, Pre- and Post-Treatment Period
  time.plot = 2008:2020
)

```

```{r run SCM}
synth.out <- synth(dataprep.out)
```

```{r analyze and visualize results}
synth.tables <- synth.tab(dataprep.res = dataprep.out, synth.res = synth.out)

# Plot the results
path.plot(dataprep.res = dataprep.out, synth.res = synth.out, Ylab = "Employment Rate", Xlab = "Year", Main = "SCM for Hospital Closure")
gaps.plot(dataprep.res = dataprep.out, synth.res = synth.out, Ylab = "Gap in Employment Rate", Xlab = "Year", Main = "SCM Gap Plot")

```